DROP TYPE "account_type";--> statement-breakpoint
DROP TYPE "attendance_status";--> statement-breakpoint
DROP TYPE "expenditure_status";--> statement-breakpoint
DROP TYPE "expenditure_type";--> statement-breakpoint
DROP TYPE "goods_receipt_status";--> statement-breakpoint
DROP TYPE "integration_provider";--> statement-breakpoint
DROP TYPE "invoice_status";--> statement-breakpoint
DROP TYPE "leave_status";--> statement-breakpoint
DROP TYPE "leave_type";--> statement-breakpoint
DROP TYPE "moka_scrap_status";--> statement-breakpoint
DROP TYPE "moka_scrap_type";--> statement-breakpoint
DROP TYPE "moka_sync_trigger_mode";--> statement-breakpoint
DROP TYPE "payment_method_category";--> statement-breakpoint
DROP TYPE "payment_method";--> statement-breakpoint
DROP TYPE "payment_type";--> statement-breakpoint
DROP TYPE "payroll_adjustment_type";--> statement-breakpoint
DROP TYPE "payroll_status";--> statement-breakpoint
DROP TYPE "product_status";--> statement-breakpoint
DROP TYPE "purchase_order_status";--> statement-breakpoint
DROP TYPE "purchase_request_status";--> statement-breakpoint
DROP TYPE "sales_order_source";--> statement-breakpoint
DROP TYPE "sales_order_status";--> statement-breakpoint
DROP TYPE "stock_adjustment_type";--> statement-breakpoint
DROP TYPE "transaction_type";--> statement-breakpoint
DROP TYPE "work_order_status";