preload = ["./src/core/otel.ts"]

[console]
depth = 10

[test]
root = "src/tests"
preload = ["./src/tests/setup.ts"]
pathIgnorePatterns = [
	# 
	"**/tests-backup/**/**",
]
concurrentTestGlob = "**/integration/*.test.ts"
