preload = ["./src/infra/otel/otel.ts"]

[console]
depth = 1000

[test]
root = "src/tests"
preload = ["./src/tests/setup.ts"]
concurrentTestGlob = "**/integration/*.test.ts"
coverageSkipTestFiles = true
coverageReporter = ["text", "lcov"]
coverageDir = "coverage"
