/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppSplatRouteImport } from './routes/_app/$'
import { Route as AppProductsIndexRouteImport } from './routes/_app/products/index'
import { Route as AppMaterialsIndexRouteImport } from './routes/_app/materials/index'
import { Route as AppSettingsTabRouteImport } from './routes/_app/settings/_tab'
import { Route as AppProductsIdRouteImport } from './routes/_app/products/$id'
import { Route as AppMaterialsUomRouteImport } from './routes/_app/materials/uom'
import { Route as AppMaterialsCreateRouteImport } from './routes/_app/materials/create'
import { Route as AppMaterialsCategoryRouteImport } from './routes/_app/materials/category'
import { Route as AppMaterialsIdRouteImport } from './routes/_app/materials/$id'
import { Route as AppExamplesPageNewRouteImport } from './routes/_app/examples/page-new'
import { Route as AppExamplesFormComponentsRouteImport } from './routes/_app/examples/form-components'
import { Route as AppExamplesDataTableRouteImport } from './routes/_app/examples/data-table'
import { Route as AppExamplesTableIndexRouteImport } from './routes/_app/examples/table/index'
import { Route as AppExamplesSearchIndexRouteImport } from './routes/_app/examples/search/index'
import { Route as AppExamplesPageLayoutsIndexRouteImport } from './routes/_app/examples/page-layouts/index'
import { Route as AppExamplesLayoutsIndexRouteImport } from './routes/_app/examples/layouts/index'
import { Route as AppExamplesFormIndexRouteImport } from './routes/_app/examples/form/index'
import { Route as AppExamplesDialogFormIndexRouteImport } from './routes/_app/examples/dialog-form/index'
import { Route as AppExamplesDetailsIndexRouteImport } from './routes/_app/examples/details/index'
import { Route as AppExamplesDetailIndexRouteImport } from './routes/_app/examples/detail/index'
import { Route as AppExamplesDashboardIndexRouteImport } from './routes/_app/examples/dashboard/index'
import { Route as AppExamplesComplexFormIndexRouteImport } from './routes/_app/examples/complex-form/index'
import { Route as AppExamplesChartsIndexRouteImport } from './routes/_app/examples/charts/index'
import { Route as AppSettingsUserCreateRouteImport } from './routes/_app/settings/user.create'
import { Route as AppSettingsUserIdRouteImport } from './routes/_app/settings/user.$id'
import { Route as AppSettingsLocationCreateRouteImport } from './routes/_app/settings/location.create'
import { Route as AppSettingsLocationIdRouteImport } from './routes/_app/settings/location.$id'
import { Route as AppSettingsTabUserRouteImport } from './routes/_app/settings/_tab.user'
import { Route as AppSettingsTabRoleRouteImport } from './routes/_app/settings/_tab.role'
import { Route as AppSettingsTabLocationRouteImport } from './routes/_app/settings/_tab.location'
import { Route as AppExamplesLayoutsTwoRouteImport } from './routes/_app/examples/layouts/two'
import { Route as AppExamplesLayoutsOneRouteImport } from './routes/_app/examples/layouts/one'

const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMaterialsIndexRoute = AppMaterialsIndexRouteImport.update({
  id: '/materials/',
  path: '/materials/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsTabRoute = AppSettingsTabRouteImport.update({
  id: '/settings/_tab',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProductsIdRoute = AppProductsIdRouteImport.update({
  id: '/products/$id',
  path: '/products/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMaterialsUomRoute = AppMaterialsUomRouteImport.update({
  id: '/materials/uom',
  path: '/materials/uom',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMaterialsCreateRoute = AppMaterialsCreateRouteImport.update({
  id: '/materials/create',
  path: '/materials/create',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMaterialsCategoryRoute = AppMaterialsCategoryRouteImport.update({
  id: '/materials/category',
  path: '/materials/category',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMaterialsIdRoute = AppMaterialsIdRouteImport.update({
  id: '/materials/$id',
  path: '/materials/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppExamplesPageNewRoute = AppExamplesPageNewRouteImport.update({
  id: '/examples/page-new',
  path: '/examples/page-new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppExamplesFormComponentsRoute =
  AppExamplesFormComponentsRouteImport.update({
    id: '/examples/form-components',
    path: '/examples/form-components',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppExamplesDataTableRoute = AppExamplesDataTableRouteImport.update({
  id: '/examples/data-table',
  path: '/examples/data-table',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppExamplesTableIndexRoute = AppExamplesTableIndexRouteImport.update({
  id: '/examples/table/',
  path: '/examples/table/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppExamplesSearchIndexRoute = AppExamplesSearchIndexRouteImport.update({
  id: '/examples/search/',
  path: '/examples/search/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppExamplesPageLayoutsIndexRoute =
  AppExamplesPageLayoutsIndexRouteImport.update({
    id: '/examples/page-layouts/',
    path: '/examples/page-layouts/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppExamplesLayoutsIndexRoute = AppExamplesLayoutsIndexRouteImport.update({
  id: '/examples/layouts/',
  path: '/examples/layouts/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppExamplesFormIndexRoute = AppExamplesFormIndexRouteImport.update({
  id: '/examples/form/',
  path: '/examples/form/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppExamplesDialogFormIndexRoute =
  AppExamplesDialogFormIndexRouteImport.update({
    id: '/examples/dialog-form/',
    path: '/examples/dialog-form/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppExamplesDetailsIndexRoute = AppExamplesDetailsIndexRouteImport.update({
  id: '/examples/details/',
  path: '/examples/details/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppExamplesDetailIndexRoute = AppExamplesDetailIndexRouteImport.update({
  id: '/examples/detail/',
  path: '/examples/detail/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppExamplesDashboardIndexRoute =
  AppExamplesDashboardIndexRouteImport.update({
    id: '/examples/dashboard/',
    path: '/examples/dashboard/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppExamplesComplexFormIndexRoute =
  AppExamplesComplexFormIndexRouteImport.update({
    id: '/examples/complex-form/',
    path: '/examples/complex-form/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppExamplesChartsIndexRoute = AppExamplesChartsIndexRouteImport.update({
  id: '/examples/charts/',
  path: '/examples/charts/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsUserCreateRoute = AppSettingsUserCreateRouteImport.update({
  id: '/settings/user/create',
  path: '/settings/user/create',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsUserIdRoute = AppSettingsUserIdRouteImport.update({
  id: '/settings/user/$id',
  path: '/settings/user/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsLocationCreateRoute =
  AppSettingsLocationCreateRouteImport.update({
    id: '/settings/location/create',
    path: '/settings/location/create',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppSettingsLocationIdRoute = AppSettingsLocationIdRouteImport.update({
  id: '/settings/location/$id',
  path: '/settings/location/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsTabUserRoute = AppSettingsTabUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => AppSettingsTabRoute,
} as any)
const AppSettingsTabRoleRoute = AppSettingsTabRoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => AppSettingsTabRoute,
} as any)
const AppSettingsTabLocationRoute = AppSettingsTabLocationRouteImport.update({
  id: '/location',
  path: '/location',
  getParentRoute: () => AppSettingsTabRoute,
} as any)
const AppExamplesLayoutsTwoRoute = AppExamplesLayoutsTwoRouteImport.update({
  id: '/examples/layouts/two',
  path: '/examples/layouts/two',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppExamplesLayoutsOneRoute = AppExamplesLayoutsOneRouteImport.update({
  id: '/examples/layouts/one',
  path: '/examples/layouts/one',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/$': typeof AppSplatRoute
  '/login': typeof AuthLoginRoute
  '/examples/data-table': typeof AppExamplesDataTableRoute
  '/examples/form-components': typeof AppExamplesFormComponentsRoute
  '/examples/page-new': typeof AppExamplesPageNewRoute
  '/materials/$id': typeof AppMaterialsIdRoute
  '/materials/category': typeof AppMaterialsCategoryRoute
  '/materials/create': typeof AppMaterialsCreateRoute
  '/materials/uom': typeof AppMaterialsUomRoute
  '/products/$id': typeof AppProductsIdRoute
  '/settings': typeof AppSettingsTabRouteWithChildren
  '/materials/': typeof AppMaterialsIndexRoute
  '/products/': typeof AppProductsIndexRoute
  '/examples/layouts/one': typeof AppExamplesLayoutsOneRoute
  '/examples/layouts/two': typeof AppExamplesLayoutsTwoRoute
  '/settings/location': typeof AppSettingsTabLocationRoute
  '/settings/role': typeof AppSettingsTabRoleRoute
  '/settings/user': typeof AppSettingsTabUserRoute
  '/settings/location/$id': typeof AppSettingsLocationIdRoute
  '/settings/location/create': typeof AppSettingsLocationCreateRoute
  '/settings/user/$id': typeof AppSettingsUserIdRoute
  '/settings/user/create': typeof AppSettingsUserCreateRoute
  '/examples/charts/': typeof AppExamplesChartsIndexRoute
  '/examples/complex-form/': typeof AppExamplesComplexFormIndexRoute
  '/examples/dashboard/': typeof AppExamplesDashboardIndexRoute
  '/examples/detail/': typeof AppExamplesDetailIndexRoute
  '/examples/details/': typeof AppExamplesDetailsIndexRoute
  '/examples/dialog-form/': typeof AppExamplesDialogFormIndexRoute
  '/examples/form/': typeof AppExamplesFormIndexRoute
  '/examples/layouts/': typeof AppExamplesLayoutsIndexRoute
  '/examples/page-layouts/': typeof AppExamplesPageLayoutsIndexRoute
  '/examples/search/': typeof AppExamplesSearchIndexRoute
  '/examples/table/': typeof AppExamplesTableIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/$': typeof AppSplatRoute
  '/login': typeof AuthLoginRoute
  '/examples/data-table': typeof AppExamplesDataTableRoute
  '/examples/form-components': typeof AppExamplesFormComponentsRoute
  '/examples/page-new': typeof AppExamplesPageNewRoute
  '/materials/$id': typeof AppMaterialsIdRoute
  '/materials/category': typeof AppMaterialsCategoryRoute
  '/materials/create': typeof AppMaterialsCreateRoute
  '/materials/uom': typeof AppMaterialsUomRoute
  '/products/$id': typeof AppProductsIdRoute
  '/settings': typeof AppSettingsTabRouteWithChildren
  '/materials': typeof AppMaterialsIndexRoute
  '/products': typeof AppProductsIndexRoute
  '/examples/layouts/one': typeof AppExamplesLayoutsOneRoute
  '/examples/layouts/two': typeof AppExamplesLayoutsTwoRoute
  '/settings/location': typeof AppSettingsTabLocationRoute
  '/settings/role': typeof AppSettingsTabRoleRoute
  '/settings/user': typeof AppSettingsTabUserRoute
  '/settings/location/$id': typeof AppSettingsLocationIdRoute
  '/settings/location/create': typeof AppSettingsLocationCreateRoute
  '/settings/user/$id': typeof AppSettingsUserIdRoute
  '/settings/user/create': typeof AppSettingsUserCreateRoute
  '/examples/charts': typeof AppExamplesChartsIndexRoute
  '/examples/complex-form': typeof AppExamplesComplexFormIndexRoute
  '/examples/dashboard': typeof AppExamplesDashboardIndexRoute
  '/examples/detail': typeof AppExamplesDetailIndexRoute
  '/examples/details': typeof AppExamplesDetailsIndexRoute
  '/examples/dialog-form': typeof AppExamplesDialogFormIndexRoute
  '/examples/form': typeof AppExamplesFormIndexRoute
  '/examples/layouts': typeof AppExamplesLayoutsIndexRoute
  '/examples/page-layouts': typeof AppExamplesPageLayoutsIndexRoute
  '/examples/search': typeof AppExamplesSearchIndexRoute
  '/examples/table': typeof AppExamplesTableIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_app/$': typeof AppSplatRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_app/': typeof AppIndexRoute
  '/_app/examples/data-table': typeof AppExamplesDataTableRoute
  '/_app/examples/form-components': typeof AppExamplesFormComponentsRoute
  '/_app/examples/page-new': typeof AppExamplesPageNewRoute
  '/_app/materials/$id': typeof AppMaterialsIdRoute
  '/_app/materials/category': typeof AppMaterialsCategoryRoute
  '/_app/materials/create': typeof AppMaterialsCreateRoute
  '/_app/materials/uom': typeof AppMaterialsUomRoute
  '/_app/products/$id': typeof AppProductsIdRoute
  '/_app/settings/_tab': typeof AppSettingsTabRouteWithChildren
  '/_app/materials/': typeof AppMaterialsIndexRoute
  '/_app/products/': typeof AppProductsIndexRoute
  '/_app/examples/layouts/one': typeof AppExamplesLayoutsOneRoute
  '/_app/examples/layouts/two': typeof AppExamplesLayoutsTwoRoute
  '/_app/settings/_tab/location': typeof AppSettingsTabLocationRoute
  '/_app/settings/_tab/role': typeof AppSettingsTabRoleRoute
  '/_app/settings/_tab/user': typeof AppSettingsTabUserRoute
  '/_app/settings/location/$id': typeof AppSettingsLocationIdRoute
  '/_app/settings/location/create': typeof AppSettingsLocationCreateRoute
  '/_app/settings/user/$id': typeof AppSettingsUserIdRoute
  '/_app/settings/user/create': typeof AppSettingsUserCreateRoute
  '/_app/examples/charts/': typeof AppExamplesChartsIndexRoute
  '/_app/examples/complex-form/': typeof AppExamplesComplexFormIndexRoute
  '/_app/examples/dashboard/': typeof AppExamplesDashboardIndexRoute
  '/_app/examples/detail/': typeof AppExamplesDetailIndexRoute
  '/_app/examples/details/': typeof AppExamplesDetailsIndexRoute
  '/_app/examples/dialog-form/': typeof AppExamplesDialogFormIndexRoute
  '/_app/examples/form/': typeof AppExamplesFormIndexRoute
  '/_app/examples/layouts/': typeof AppExamplesLayoutsIndexRoute
  '/_app/examples/page-layouts/': typeof AppExamplesPageLayoutsIndexRoute
  '/_app/examples/search/': typeof AppExamplesSearchIndexRoute
  '/_app/examples/table/': typeof AppExamplesTableIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/login'
    | '/examples/data-table'
    | '/examples/form-components'
    | '/examples/page-new'
    | '/materials/$id'
    | '/materials/category'
    | '/materials/create'
    | '/materials/uom'
    | '/products/$id'
    | '/settings'
    | '/materials/'
    | '/products/'
    | '/examples/layouts/one'
    | '/examples/layouts/two'
    | '/settings/location'
    | '/settings/role'
    | '/settings/user'
    | '/settings/location/$id'
    | '/settings/location/create'
    | '/settings/user/$id'
    | '/settings/user/create'
    | '/examples/charts/'
    | '/examples/complex-form/'
    | '/examples/dashboard/'
    | '/examples/detail/'
    | '/examples/details/'
    | '/examples/dialog-form/'
    | '/examples/form/'
    | '/examples/layouts/'
    | '/examples/page-layouts/'
    | '/examples/search/'
    | '/examples/table/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/login'
    | '/examples/data-table'
    | '/examples/form-components'
    | '/examples/page-new'
    | '/materials/$id'
    | '/materials/category'
    | '/materials/create'
    | '/materials/uom'
    | '/products/$id'
    | '/settings'
    | '/materials'
    | '/products'
    | '/examples/layouts/one'
    | '/examples/layouts/two'
    | '/settings/location'
    | '/settings/role'
    | '/settings/user'
    | '/settings/location/$id'
    | '/settings/location/create'
    | '/settings/user/$id'
    | '/settings/user/create'
    | '/examples/charts'
    | '/examples/complex-form'
    | '/examples/dashboard'
    | '/examples/detail'
    | '/examples/details'
    | '/examples/dialog-form'
    | '/examples/form'
    | '/examples/layouts'
    | '/examples/page-layouts'
    | '/examples/search'
    | '/examples/table'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_app/$'
    | '/_auth/login'
    | '/_app/'
    | '/_app/examples/data-table'
    | '/_app/examples/form-components'
    | '/_app/examples/page-new'
    | '/_app/materials/$id'
    | '/_app/materials/category'
    | '/_app/materials/create'
    | '/_app/materials/uom'
    | '/_app/products/$id'
    | '/_app/settings/_tab'
    | '/_app/materials/'
    | '/_app/products/'
    | '/_app/examples/layouts/one'
    | '/_app/examples/layouts/two'
    | '/_app/settings/_tab/location'
    | '/_app/settings/_tab/role'
    | '/_app/settings/_tab/user'
    | '/_app/settings/location/$id'
    | '/_app/settings/location/create'
    | '/_app/settings/user/$id'
    | '/_app/settings/user/create'
    | '/_app/examples/charts/'
    | '/_app/examples/complex-form/'
    | '/_app/examples/dashboard/'
    | '/_app/examples/detail/'
    | '/_app/examples/details/'
    | '/_app/examples/dialog-form/'
    | '/_app/examples/form/'
    | '/_app/examples/layouts/'
    | '/_app/examples/page-layouts/'
    | '/_app/examples/search/'
    | '/_app/examples/table/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/$': {
      id: '/_app/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/products/': {
      id: '/_app/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/materials/': {
      id: '/_app/materials/'
      path: '/materials'
      fullPath: '/materials/'
      preLoaderRoute: typeof AppMaterialsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings/_tab': {
      id: '/_app/settings/_tab'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsTabRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/products/$id': {
      id: '/_app/products/$id'
      path: '/products/$id'
      fullPath: '/products/$id'
      preLoaderRoute: typeof AppProductsIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/materials/uom': {
      id: '/_app/materials/uom'
      path: '/materials/uom'
      fullPath: '/materials/uom'
      preLoaderRoute: typeof AppMaterialsUomRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/materials/create': {
      id: '/_app/materials/create'
      path: '/materials/create'
      fullPath: '/materials/create'
      preLoaderRoute: typeof AppMaterialsCreateRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/materials/category': {
      id: '/_app/materials/category'
      path: '/materials/category'
      fullPath: '/materials/category'
      preLoaderRoute: typeof AppMaterialsCategoryRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/materials/$id': {
      id: '/_app/materials/$id'
      path: '/materials/$id'
      fullPath: '/materials/$id'
      preLoaderRoute: typeof AppMaterialsIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/examples/page-new': {
      id: '/_app/examples/page-new'
      path: '/examples/page-new'
      fullPath: '/examples/page-new'
      preLoaderRoute: typeof AppExamplesPageNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/examples/form-components': {
      id: '/_app/examples/form-components'
      path: '/examples/form-components'
      fullPath: '/examples/form-components'
      preLoaderRoute: typeof AppExamplesFormComponentsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/examples/data-table': {
      id: '/_app/examples/data-table'
      path: '/examples/data-table'
      fullPath: '/examples/data-table'
      preLoaderRoute: typeof AppExamplesDataTableRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/examples/table/': {
      id: '/_app/examples/table/'
      path: '/examples/table'
      fullPath: '/examples/table/'
      preLoaderRoute: typeof AppExamplesTableIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/examples/search/': {
      id: '/_app/examples/search/'
      path: '/examples/search'
      fullPath: '/examples/search/'
      preLoaderRoute: typeof AppExamplesSearchIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/examples/page-layouts/': {
      id: '/_app/examples/page-layouts/'
      path: '/examples/page-layouts'
      fullPath: '/examples/page-layouts/'
      preLoaderRoute: typeof AppExamplesPageLayoutsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/examples/layouts/': {
      id: '/_app/examples/layouts/'
      path: '/examples/layouts'
      fullPath: '/examples/layouts/'
      preLoaderRoute: typeof AppExamplesLayoutsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/examples/form/': {
      id: '/_app/examples/form/'
      path: '/examples/form'
      fullPath: '/examples/form/'
      preLoaderRoute: typeof AppExamplesFormIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/examples/dialog-form/': {
      id: '/_app/examples/dialog-form/'
      path: '/examples/dialog-form'
      fullPath: '/examples/dialog-form/'
      preLoaderRoute: typeof AppExamplesDialogFormIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/examples/details/': {
      id: '/_app/examples/details/'
      path: '/examples/details'
      fullPath: '/examples/details/'
      preLoaderRoute: typeof AppExamplesDetailsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/examples/detail/': {
      id: '/_app/examples/detail/'
      path: '/examples/detail'
      fullPath: '/examples/detail/'
      preLoaderRoute: typeof AppExamplesDetailIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/examples/dashboard/': {
      id: '/_app/examples/dashboard/'
      path: '/examples/dashboard'
      fullPath: '/examples/dashboard/'
      preLoaderRoute: typeof AppExamplesDashboardIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/examples/complex-form/': {
      id: '/_app/examples/complex-form/'
      path: '/examples/complex-form'
      fullPath: '/examples/complex-form/'
      preLoaderRoute: typeof AppExamplesComplexFormIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/examples/charts/': {
      id: '/_app/examples/charts/'
      path: '/examples/charts'
      fullPath: '/examples/charts/'
      preLoaderRoute: typeof AppExamplesChartsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings/user/create': {
      id: '/_app/settings/user/create'
      path: '/settings/user/create'
      fullPath: '/settings/user/create'
      preLoaderRoute: typeof AppSettingsUserCreateRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings/user/$id': {
      id: '/_app/settings/user/$id'
      path: '/settings/user/$id'
      fullPath: '/settings/user/$id'
      preLoaderRoute: typeof AppSettingsUserIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings/location/create': {
      id: '/_app/settings/location/create'
      path: '/settings/location/create'
      fullPath: '/settings/location/create'
      preLoaderRoute: typeof AppSettingsLocationCreateRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings/location/$id': {
      id: '/_app/settings/location/$id'
      path: '/settings/location/$id'
      fullPath: '/settings/location/$id'
      preLoaderRoute: typeof AppSettingsLocationIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings/_tab/user': {
      id: '/_app/settings/_tab/user'
      path: '/user'
      fullPath: '/settings/user'
      preLoaderRoute: typeof AppSettingsTabUserRouteImport
      parentRoute: typeof AppSettingsTabRoute
    }
    '/_app/settings/_tab/role': {
      id: '/_app/settings/_tab/role'
      path: '/role'
      fullPath: '/settings/role'
      preLoaderRoute: typeof AppSettingsTabRoleRouteImport
      parentRoute: typeof AppSettingsTabRoute
    }
    '/_app/settings/_tab/location': {
      id: '/_app/settings/_tab/location'
      path: '/location'
      fullPath: '/settings/location'
      preLoaderRoute: typeof AppSettingsTabLocationRouteImport
      parentRoute: typeof AppSettingsTabRoute
    }
    '/_app/examples/layouts/two': {
      id: '/_app/examples/layouts/two'
      path: '/examples/layouts/two'
      fullPath: '/examples/layouts/two'
      preLoaderRoute: typeof AppExamplesLayoutsTwoRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/examples/layouts/one': {
      id: '/_app/examples/layouts/one'
      path: '/examples/layouts/one'
      fullPath: '/examples/layouts/one'
      preLoaderRoute: typeof AppExamplesLayoutsOneRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppSettingsTabRouteChildren {
  AppSettingsTabLocationRoute: typeof AppSettingsTabLocationRoute
  AppSettingsTabRoleRoute: typeof AppSettingsTabRoleRoute
  AppSettingsTabUserRoute: typeof AppSettingsTabUserRoute
}

const AppSettingsTabRouteChildren: AppSettingsTabRouteChildren = {
  AppSettingsTabLocationRoute: AppSettingsTabLocationRoute,
  AppSettingsTabRoleRoute: AppSettingsTabRoleRoute,
  AppSettingsTabUserRoute: AppSettingsTabUserRoute,
}

const AppSettingsTabRouteWithChildren = AppSettingsTabRoute._addFileChildren(
  AppSettingsTabRouteChildren,
)

interface AppRouteRouteChildren {
  AppSplatRoute: typeof AppSplatRoute
  AppIndexRoute: typeof AppIndexRoute
  AppExamplesDataTableRoute: typeof AppExamplesDataTableRoute
  AppExamplesFormComponentsRoute: typeof AppExamplesFormComponentsRoute
  AppExamplesPageNewRoute: typeof AppExamplesPageNewRoute
  AppMaterialsIdRoute: typeof AppMaterialsIdRoute
  AppMaterialsCategoryRoute: typeof AppMaterialsCategoryRoute
  AppMaterialsCreateRoute: typeof AppMaterialsCreateRoute
  AppMaterialsUomRoute: typeof AppMaterialsUomRoute
  AppProductsIdRoute: typeof AppProductsIdRoute
  AppSettingsTabRoute: typeof AppSettingsTabRouteWithChildren
  AppMaterialsIndexRoute: typeof AppMaterialsIndexRoute
  AppProductsIndexRoute: typeof AppProductsIndexRoute
  AppExamplesLayoutsOneRoute: typeof AppExamplesLayoutsOneRoute
  AppExamplesLayoutsTwoRoute: typeof AppExamplesLayoutsTwoRoute
  AppSettingsLocationIdRoute: typeof AppSettingsLocationIdRoute
  AppSettingsLocationCreateRoute: typeof AppSettingsLocationCreateRoute
  AppSettingsUserIdRoute: typeof AppSettingsUserIdRoute
  AppSettingsUserCreateRoute: typeof AppSettingsUserCreateRoute
  AppExamplesChartsIndexRoute: typeof AppExamplesChartsIndexRoute
  AppExamplesComplexFormIndexRoute: typeof AppExamplesComplexFormIndexRoute
  AppExamplesDashboardIndexRoute: typeof AppExamplesDashboardIndexRoute
  AppExamplesDetailIndexRoute: typeof AppExamplesDetailIndexRoute
  AppExamplesDetailsIndexRoute: typeof AppExamplesDetailsIndexRoute
  AppExamplesDialogFormIndexRoute: typeof AppExamplesDialogFormIndexRoute
  AppExamplesFormIndexRoute: typeof AppExamplesFormIndexRoute
  AppExamplesLayoutsIndexRoute: typeof AppExamplesLayoutsIndexRoute
  AppExamplesPageLayoutsIndexRoute: typeof AppExamplesPageLayoutsIndexRoute
  AppExamplesSearchIndexRoute: typeof AppExamplesSearchIndexRoute
  AppExamplesTableIndexRoute: typeof AppExamplesTableIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppSplatRoute: AppSplatRoute,
  AppIndexRoute: AppIndexRoute,
  AppExamplesDataTableRoute: AppExamplesDataTableRoute,
  AppExamplesFormComponentsRoute: AppExamplesFormComponentsRoute,
  AppExamplesPageNewRoute: AppExamplesPageNewRoute,
  AppMaterialsIdRoute: AppMaterialsIdRoute,
  AppMaterialsCategoryRoute: AppMaterialsCategoryRoute,
  AppMaterialsCreateRoute: AppMaterialsCreateRoute,
  AppMaterialsUomRoute: AppMaterialsUomRoute,
  AppProductsIdRoute: AppProductsIdRoute,
  AppSettingsTabRoute: AppSettingsTabRouteWithChildren,
  AppMaterialsIndexRoute: AppMaterialsIndexRoute,
  AppProductsIndexRoute: AppProductsIndexRoute,
  AppExamplesLayoutsOneRoute: AppExamplesLayoutsOneRoute,
  AppExamplesLayoutsTwoRoute: AppExamplesLayoutsTwoRoute,
  AppSettingsLocationIdRoute: AppSettingsLocationIdRoute,
  AppSettingsLocationCreateRoute: AppSettingsLocationCreateRoute,
  AppSettingsUserIdRoute: AppSettingsUserIdRoute,
  AppSettingsUserCreateRoute: AppSettingsUserCreateRoute,
  AppExamplesChartsIndexRoute: AppExamplesChartsIndexRoute,
  AppExamplesComplexFormIndexRoute: AppExamplesComplexFormIndexRoute,
  AppExamplesDashboardIndexRoute: AppExamplesDashboardIndexRoute,
  AppExamplesDetailIndexRoute: AppExamplesDetailIndexRoute,
  AppExamplesDetailsIndexRoute: AppExamplesDetailsIndexRoute,
  AppExamplesDialogFormIndexRoute: AppExamplesDialogFormIndexRoute,
  AppExamplesFormIndexRoute: AppExamplesFormIndexRoute,
  AppExamplesLayoutsIndexRoute: AppExamplesLayoutsIndexRoute,
  AppExamplesPageLayoutsIndexRoute: AppExamplesPageLayoutsIndexRoute,
  AppExamplesSearchIndexRoute: AppExamplesSearchIndexRoute,
  AppExamplesTableIndexRoute: AppExamplesTableIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
