/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as DesignSystemRouteImport } from './routes/design-system'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedDemoRouteImport } from './routes/_authenticated/demo'
import { Route as AuthenticatedInventoryOpnameRouteImport } from './routes/_authenticated/inventory/opname'
import { Route as AuthenticatedInventoryStockRouteImport } from './routes/_authenticated/inventory/stock'
import { Route as AuthenticatedInventoryTransfersRouteImport } from './routes/_authenticated/inventory/transfers'
import { Route as AuthenticatedMasterLocationsRouteImport } from './routes/_authenticated/master/locations'
import { Route as AuthenticatedMasterMaterialsRouteImport } from './routes/_authenticated/master/materials'
import { Route as AuthenticatedMasterMenuRouteImport } from './routes/_authenticated/master/menu'
import { Route as AuthenticatedMasterPaymentMethodsRouteImport } from './routes/_authenticated/master/payment-methods'
import { Route as AuthenticatedMasterSuppliersRouteImport } from './routes/_authenticated/master/suppliers'
import { Route as AuthenticatedMasterUomRouteImport } from './routes/_authenticated/master/uom'
import { Route as AuthenticatedPosShiftsRouteImport } from './routes/_authenticated/pos/shifts'
import { Route as AuthenticatedPosTablesRouteImport } from './routes/_authenticated/pos/tables'
import { Route as AuthenticatedPosVouchersRouteImport } from './routes/_authenticated/pos/vouchers'
import { Route as AuthenticatedSettingsCompanyRouteImport } from './routes/_authenticated/settings/company'
import { Route as AuthenticatedSettingsRolesRouteImport } from './routes/_authenticated/settings/roles'
import { Route as AuthenticatedSettingsUsersRouteImport } from './routes/_authenticated/settings/users'

const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignSystemRoute = DesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDemoRoute = AuthenticatedDemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedInventoryOpnameRoute =
  AuthenticatedInventoryOpnameRouteImport.update({
    id: '/inventory/opname',
    path: '/inventory/opname',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryStockRoute =
  AuthenticatedInventoryStockRouteImport.update({
    id: '/inventory/stock',
    path: '/inventory/stock',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedInventoryTransfersRoute =
  AuthenticatedInventoryTransfersRouteImport.update({
    id: '/inventory/transfers',
    path: '/inventory/transfers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMasterLocationsRoute =
  AuthenticatedMasterLocationsRouteImport.update({
    id: '/master/locations',
    path: '/master/locations',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMasterMaterialsRoute =
  AuthenticatedMasterMaterialsRouteImport.update({
    id: '/master/materials',
    path: '/master/materials',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMasterMenuRoute = AuthenticatedMasterMenuRouteImport.update({
  id: '/master/menu',
  path: '/master/menu',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedMasterPaymentMethodsRoute =
  AuthenticatedMasterPaymentMethodsRouteImport.update({
    id: '/master/payment-methods',
    path: '/master/payment-methods',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMasterSuppliersRoute =
  AuthenticatedMasterSuppliersRouteImport.update({
    id: '/master/suppliers',
    path: '/master/suppliers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMasterUomRoute = AuthenticatedMasterUomRouteImport.update({
  id: '/master/uom',
  path: '/master/uom',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPosShiftsRoute = AuthenticatedPosShiftsRouteImport.update({
  id: '/pos/shifts',
  path: '/pos/shifts',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPosTablesRoute = AuthenticatedPosTablesRouteImport.update({
  id: '/pos/tables',
  path: '/pos/tables',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPosVouchersRoute =
  AuthenticatedPosVouchersRouteImport.update({
    id: '/pos/vouchers',
    path: '/pos/vouchers',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsCompanyRoute =
  AuthenticatedSettingsCompanyRouteImport.update({
    id: '/settings/company',
    path: '/settings/company',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsRolesRoute =
  AuthenticatedSettingsRolesRouteImport.update({
    id: '/settings/roles',
    path: '/settings/roles',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsUsersRoute =
  AuthenticatedSettingsUsersRouteImport.update({
    id: '/settings/users',
    path: '/settings/users',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/design-system': typeof DesignSystemRoute
  '/login': typeof LoginRoute
  '/demo': typeof AuthenticatedDemoRoute
  '/inventory/opname': typeof AuthenticatedInventoryOpnameRoute
  '/inventory/stock': typeof AuthenticatedInventoryStockRoute
  '/inventory/transfers': typeof AuthenticatedInventoryTransfersRoute
  '/master/locations': typeof AuthenticatedMasterLocationsRoute
  '/master/materials': typeof AuthenticatedMasterMaterialsRoute
  '/master/menu': typeof AuthenticatedMasterMenuRoute
  '/master/payment-methods': typeof AuthenticatedMasterPaymentMethodsRoute
  '/master/suppliers': typeof AuthenticatedMasterSuppliersRoute
  '/master/uom': typeof AuthenticatedMasterUomRoute
  '/pos/shifts': typeof AuthenticatedPosShiftsRoute
  '/pos/tables': typeof AuthenticatedPosTablesRoute
  '/pos/vouchers': typeof AuthenticatedPosVouchersRoute
  '/settings/company': typeof AuthenticatedSettingsCompanyRoute
  '/settings/roles': typeof AuthenticatedSettingsRolesRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
}
export interface FileRoutesByTo {
  '/design-system': typeof DesignSystemRoute
  '/login': typeof LoginRoute
  '/demo': typeof AuthenticatedDemoRoute
  '/': typeof AuthenticatedIndexRoute
  '/inventory/opname': typeof AuthenticatedInventoryOpnameRoute
  '/inventory/stock': typeof AuthenticatedInventoryStockRoute
  '/inventory/transfers': typeof AuthenticatedInventoryTransfersRoute
  '/master/locations': typeof AuthenticatedMasterLocationsRoute
  '/master/materials': typeof AuthenticatedMasterMaterialsRoute
  '/master/menu': typeof AuthenticatedMasterMenuRoute
  '/master/payment-methods': typeof AuthenticatedMasterPaymentMethodsRoute
  '/master/suppliers': typeof AuthenticatedMasterSuppliersRoute
  '/master/uom': typeof AuthenticatedMasterUomRoute
  '/pos/shifts': typeof AuthenticatedPosShiftsRoute
  '/pos/tables': typeof AuthenticatedPosTablesRoute
  '/pos/vouchers': typeof AuthenticatedPosVouchersRoute
  '/settings/company': typeof AuthenticatedSettingsCompanyRoute
  '/settings/roles': typeof AuthenticatedSettingsRolesRoute
  '/settings/users': typeof AuthenticatedSettingsUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/design-system': typeof DesignSystemRoute
  '/login': typeof LoginRoute
  '/_authenticated/demo': typeof AuthenticatedDemoRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/inventory/opname': typeof AuthenticatedInventoryOpnameRoute
  '/_authenticated/inventory/stock': typeof AuthenticatedInventoryStockRoute
  '/_authenticated/inventory/transfers': typeof AuthenticatedInventoryTransfersRoute
  '/_authenticated/master/locations': typeof AuthenticatedMasterLocationsRoute
  '/_authenticated/master/materials': typeof AuthenticatedMasterMaterialsRoute
  '/_authenticated/master/menu': typeof AuthenticatedMasterMenuRoute
  '/_authenticated/master/payment-methods': typeof AuthenticatedMasterPaymentMethodsRoute
  '/_authenticated/master/suppliers': typeof AuthenticatedMasterSuppliersRoute
  '/_authenticated/master/uom': typeof AuthenticatedMasterUomRoute
  '/_authenticated/pos/shifts': typeof AuthenticatedPosShiftsRoute
  '/_authenticated/pos/tables': typeof AuthenticatedPosTablesRoute
  '/_authenticated/pos/vouchers': typeof AuthenticatedPosVouchersRoute
  '/_authenticated/settings/company': typeof AuthenticatedSettingsCompanyRoute
  '/_authenticated/settings/roles': typeof AuthenticatedSettingsRolesRoute
  '/_authenticated/settings/users': typeof AuthenticatedSettingsUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/design-system'
    | '/login'
    | '/demo'
    | '/inventory/opname'
    | '/inventory/stock'
    | '/inventory/transfers'
    | '/master/locations'
    | '/master/materials'
    | '/master/menu'
    | '/master/payment-methods'
    | '/master/suppliers'
    | '/master/uom'
    | '/pos/shifts'
    | '/pos/tables'
    | '/pos/vouchers'
    | '/settings/company'
    | '/settings/roles'
    | '/settings/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/design-system'
    | '/login'
    | '/demo'
    | '/'
    | '/inventory/opname'
    | '/inventory/stock'
    | '/inventory/transfers'
    | '/master/locations'
    | '/master/materials'
    | '/master/menu'
    | '/master/payment-methods'
    | '/master/suppliers'
    | '/master/uom'
    | '/pos/shifts'
    | '/pos/tables'
    | '/pos/vouchers'
    | '/settings/company'
    | '/settings/roles'
    | '/settings/users'
  id:
    | '__root__'
    | '/_authenticated'
    | '/design-system'
    | '/login'
    | '/_authenticated/demo'
    | '/_authenticated/'
    | '/_authenticated/inventory/opname'
    | '/_authenticated/inventory/stock'
    | '/_authenticated/inventory/transfers'
    | '/_authenticated/master/locations'
    | '/_authenticated/master/materials'
    | '/_authenticated/master/menu'
    | '/_authenticated/master/payment-methods'
    | '/_authenticated/master/suppliers'
    | '/_authenticated/master/uom'
    | '/_authenticated/pos/shifts'
    | '/_authenticated/pos/tables'
    | '/_authenticated/pos/vouchers'
    | '/_authenticated/settings/company'
    | '/_authenticated/settings/roles'
    | '/_authenticated/settings/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  DesignSystemRoute: typeof DesignSystemRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/design-system': {
      id: '/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof DesignSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/demo': {
      id: '/_authenticated/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof AuthenticatedDemoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/opname': {
      id: '/_authenticated/inventory/opname'
      path: '/inventory/opname'
      fullPath: '/inventory/opname'
      preLoaderRoute: typeof AuthenticatedInventoryOpnameRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/stock': {
      id: '/_authenticated/inventory/stock'
      path: '/inventory/stock'
      fullPath: '/inventory/stock'
      preLoaderRoute: typeof AuthenticatedInventoryStockRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/inventory/transfers': {
      id: '/_authenticated/inventory/transfers'
      path: '/inventory/transfers'
      fullPath: '/inventory/transfers'
      preLoaderRoute: typeof AuthenticatedInventoryTransfersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/master/locations': {
      id: '/_authenticated/master/locations'
      path: '/master/locations'
      fullPath: '/master/locations'
      preLoaderRoute: typeof AuthenticatedMasterLocationsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/master/materials': {
      id: '/_authenticated/master/materials'
      path: '/master/materials'
      fullPath: '/master/materials'
      preLoaderRoute: typeof AuthenticatedMasterMaterialsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/master/menu': {
      id: '/_authenticated/master/menu'
      path: '/master/menu'
      fullPath: '/master/menu'
      preLoaderRoute: typeof AuthenticatedMasterMenuRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/master/payment-methods': {
      id: '/_authenticated/master/payment-methods'
      path: '/master/payment-methods'
      fullPath: '/master/payment-methods'
      preLoaderRoute: typeof AuthenticatedMasterPaymentMethodsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/master/suppliers': {
      id: '/_authenticated/master/suppliers'
      path: '/master/suppliers'
      fullPath: '/master/suppliers'
      preLoaderRoute: typeof AuthenticatedMasterSuppliersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/master/uom': {
      id: '/_authenticated/master/uom'
      path: '/master/uom'
      fullPath: '/master/uom'
      preLoaderRoute: typeof AuthenticatedMasterUomRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pos/shifts': {
      id: '/_authenticated/pos/shifts'
      path: '/pos/shifts'
      fullPath: '/pos/shifts'
      preLoaderRoute: typeof AuthenticatedPosShiftsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pos/tables': {
      id: '/_authenticated/pos/tables'
      path: '/pos/tables'
      fullPath: '/pos/tables'
      preLoaderRoute: typeof AuthenticatedPosTablesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/pos/vouchers': {
      id: '/_authenticated/pos/vouchers'
      path: '/pos/vouchers'
      fullPath: '/pos/vouchers'
      preLoaderRoute: typeof AuthenticatedPosVouchersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/company': {
      id: '/_authenticated/settings/company'
      path: '/settings/company'
      fullPath: '/settings/company'
      preLoaderRoute: typeof AuthenticatedSettingsCompanyRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/roles': {
      id: '/_authenticated/settings/roles'
      path: '/settings/roles'
      fullPath: '/settings/roles'
      preLoaderRoute: typeof AuthenticatedSettingsRolesRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/users': {
      id: '/_authenticated/settings/users'
      path: '/settings/users'
      fullPath: '/settings/users'
      preLoaderRoute: typeof AuthenticatedSettingsUsersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDemoRoute: typeof AuthenticatedDemoRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedInventoryOpnameRoute: typeof AuthenticatedInventoryOpnameRoute
  AuthenticatedInventoryStockRoute: typeof AuthenticatedInventoryStockRoute
  AuthenticatedInventoryTransfersRoute: typeof AuthenticatedInventoryTransfersRoute
  AuthenticatedMasterLocationsRoute: typeof AuthenticatedMasterLocationsRoute
  AuthenticatedMasterMaterialsRoute: typeof AuthenticatedMasterMaterialsRoute
  AuthenticatedMasterMenuRoute: typeof AuthenticatedMasterMenuRoute
  AuthenticatedMasterPaymentMethodsRoute: typeof AuthenticatedMasterPaymentMethodsRoute
  AuthenticatedMasterSuppliersRoute: typeof AuthenticatedMasterSuppliersRoute
  AuthenticatedMasterUomRoute: typeof AuthenticatedMasterUomRoute
  AuthenticatedPosShiftsRoute: typeof AuthenticatedPosShiftsRoute
  AuthenticatedPosTablesRoute: typeof AuthenticatedPosTablesRoute
  AuthenticatedPosVouchersRoute: typeof AuthenticatedPosVouchersRoute
  AuthenticatedSettingsCompanyRoute: typeof AuthenticatedSettingsCompanyRoute
  AuthenticatedSettingsRolesRoute: typeof AuthenticatedSettingsRolesRoute
  AuthenticatedSettingsUsersRoute: typeof AuthenticatedSettingsUsersRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDemoRoute: AuthenticatedDemoRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedInventoryOpnameRoute: AuthenticatedInventoryOpnameRoute,
  AuthenticatedInventoryStockRoute: AuthenticatedInventoryStockRoute,
  AuthenticatedInventoryTransfersRoute: AuthenticatedInventoryTransfersRoute,
  AuthenticatedMasterLocationsRoute: AuthenticatedMasterLocationsRoute,
  AuthenticatedMasterMaterialsRoute: AuthenticatedMasterMaterialsRoute,
  AuthenticatedMasterMenuRoute: AuthenticatedMasterMenuRoute,
  AuthenticatedMasterPaymentMethodsRoute:
    AuthenticatedMasterPaymentMethodsRoute,
  AuthenticatedMasterSuppliersRoute: AuthenticatedMasterSuppliersRoute,
  AuthenticatedMasterUomRoute: AuthenticatedMasterUomRoute,
  AuthenticatedPosShiftsRoute: AuthenticatedPosShiftsRoute,
  AuthenticatedPosTablesRoute: AuthenticatedPosTablesRoute,
  AuthenticatedPosVouchersRoute: AuthenticatedPosVouchersRoute,
  AuthenticatedSettingsCompanyRoute: AuthenticatedSettingsCompanyRoute,
  AuthenticatedSettingsRolesRoute: AuthenticatedSettingsRolesRoute,
  AuthenticatedSettingsUsersRoute: AuthenticatedSettingsUsersRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  DesignSystemRoute: DesignSystemRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
