/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteImport } from './routes/_docs'
import { Route as AuthRouteRouteImport } from './routes/_auth/route'
import { Route as AppRouteRouteImport } from './routes/_app/route'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AuthLoginRouteImport } from './routes/_auth/login'
import { Route as AppSplatRouteImport } from './routes/_app/$'
import { Route as DocsDocsIndexRouteImport } from './routes/_docs/docs/index'
import { Route as AppProductIndexRouteImport } from './routes/_app/product/index'
import { Route as AppMaterialIndexRouteImport } from './routes/_app/material/index'
import { Route as AppLocationIndexRouteImport } from './routes/_app/location/index'
import { Route as DocsDocsLayerRouteImport } from './routes/_docs/docs/$layer'
import { Route as AppSettingsTabRouteImport } from './routes/_app/settings/_tab'
import { Route as AppSalesOrdersRouteImport } from './routes/_app/sales/orders'
import { Route as AppSalesCustomersRouteImport } from './routes/_app/sales/customers'
import { Route as AppProductionWorkOrdersRouteImport } from './routes/_app/production/work-orders'
import { Route as AppProductSalesTypeRouteImport } from './routes/_app/product/sales-type'
import { Route as AppProductCreateRouteImport } from './routes/_app/product/create'
import { Route as AppProductCategoryRouteImport } from './routes/_app/product/category'
import { Route as AppProductIdRouteImport } from './routes/_app/product/$id'
import { Route as AppProcurementSuppliersRouteImport } from './routes/_app/procurement/suppliers'
import { Route as AppProcurementOrdersRouteImport } from './routes/_app/procurement/orders'
import { Route as AppMokaMonitoringRouteImport } from './routes/_app/moka/monitoring'
import { Route as AppMaterialUomRouteImport } from './routes/_app/material/uom'
import { Route as AppMaterialStockRouteImport } from './routes/_app/material/stock'
import { Route as AppMaterialLedgerRouteImport } from './routes/_app/material/ledger'
import { Route as AppMaterialCreateRouteImport } from './routes/_app/material/create'
import { Route as AppMaterialCategoryRouteImport } from './routes/_app/material/category'
import { Route as AppLocationCreateRouteImport } from './routes/_app/location/create'
import { Route as AppLocationIdRouteImport } from './routes/_app/location/$id'
import { Route as AppInventorySummaryRouteImport } from './routes/_app/inventory/summary'
import { Route as AppFinanceLedgerArApRouteImport } from './routes/_app/finance/ledger-ar-ap'
import { Route as AppFinanceLedgerRouteImport } from './routes/_app/finance/ledger'
import { Route as AppFinanceExpensesRouteImport } from './routes/_app/finance/expenses'
import { Route as AppFinanceAccountsRouteImport } from './routes/_app/finance/accounts'
import { Route as AppExamplesPageNewRouteImport } from './routes/_app/examples/page-new'
import { Route as AppExamplesFormComponentsRouteImport } from './routes/_app/examples/form-components'
import { Route as AppExamplesDataTableRouteImport } from './routes/_app/examples/data-table'
import { Route as AppAnalyticsStockRouteImport } from './routes/_app/analytics/stock'
import { Route as AppAnalyticsProductionRouteImport } from './routes/_app/analytics/production'
import { Route as AppMaterialIdIndexRouteImport } from './routes/_app/material/$id.index'
import { Route as AppInventoryTransactionsIndexRouteImport } from './routes/_app/inventory/transactions/index'
import { Route as AppExamplesSearchIndexRouteImport } from './routes/_app/examples/search/index'
import { Route as AppExamplesPageLayoutsIndexRouteImport } from './routes/_app/examples/page-layouts/index'
import { Route as AppExamplesLayoutsIndexRouteImport } from './routes/_app/examples/layouts/index'
import { Route as AppExamplesFormIndexRouteImport } from './routes/_app/examples/form/index'
import { Route as AppExamplesDialogFormIndexRouteImport } from './routes/_app/examples/dialog-form/index'
import { Route as AppExamplesDetailsIndexRouteImport } from './routes/_app/examples/details/index'
import { Route as AppExamplesDetailIndexRouteImport } from './routes/_app/examples/detail/index'
import { Route as AppExamplesDashboardIndexRouteImport } from './routes/_app/examples/dashboard/index'
import { Route as AppExamplesComplexFormIndexRouteImport } from './routes/_app/examples/complex-form/index'
import { Route as AppExamplesChartsIndexRouteImport } from './routes/_app/examples/charts/index'
import { Route as AppSettingsUserCreateRouteImport } from './routes/_app/settings/user.create'
import { Route as AppSettingsUserIdRouteImport } from './routes/_app/settings/user.$id'
import { Route as AppSettingsTabUserRouteImport } from './routes/_app/settings/_tab.user'
import { Route as AppSettingsTabRoleRouteImport } from './routes/_app/settings/_tab.role'
import { Route as AppMaterialIdUpdateRouteImport } from './routes/_app/material/$id.update'
import { Route as AppMaterialIdRecipeRouteImport } from './routes/_app/material/$id.recipe'
import { Route as AppInventoryTransactionsTransferRouteImport } from './routes/_app/inventory/transactions/transfer'
import { Route as AppInventoryTransactionsAdjustmentRouteImport } from './routes/_app/inventory/transactions/adjustment'
import { Route as AppInventoryTransactionsIdRouteImport } from './routes/_app/inventory/transactions/$id'
import { Route as AppExamplesLayoutsTwoRouteImport } from './routes/_app/examples/layouts/two'
import { Route as AppExamplesLayoutsOneRouteImport } from './routes/_app/examples/layouts/one'

const DocsRoute = DocsRouteImport.update({
  id: '/_docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRouteRoute = AuthRouteRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRouteRoute = AppRouteRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AuthLoginRoute = AuthLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AuthRouteRoute,
} as any)
const AppSplatRoute = AppSplatRouteImport.update({
  id: '/$',
  path: '/$',
  getParentRoute: () => AppRouteRoute,
} as any)
const DocsDocsIndexRoute = DocsDocsIndexRouteImport.update({
  id: '/docs/',
  path: '/docs/',
  getParentRoute: () => DocsRoute,
} as any)
const AppProductIndexRoute = AppProductIndexRouteImport.update({
  id: '/product/',
  path: '/product/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMaterialIndexRoute = AppMaterialIndexRouteImport.update({
  id: '/material/',
  path: '/material/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLocationIndexRoute = AppLocationIndexRouteImport.update({
  id: '/location/',
  path: '/location/',
  getParentRoute: () => AppRouteRoute,
} as any)
const DocsDocsLayerRoute = DocsDocsLayerRouteImport.update({
  id: '/docs/$layer',
  path: '/docs/$layer',
  getParentRoute: () => DocsRoute,
} as any)
const AppSettingsTabRoute = AppSettingsTabRouteImport.update({
  id: '/settings/_tab',
  path: '/settings',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSalesOrdersRoute = AppSalesOrdersRouteImport.update({
  id: '/sales/orders',
  path: '/sales/orders',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSalesCustomersRoute = AppSalesCustomersRouteImport.update({
  id: '/sales/customers',
  path: '/sales/customers',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProductionWorkOrdersRoute = AppProductionWorkOrdersRouteImport.update({
  id: '/production/work-orders',
  path: '/production/work-orders',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProductSalesTypeRoute = AppProductSalesTypeRouteImport.update({
  id: '/product/sales-type',
  path: '/product/sales-type',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProductCreateRoute = AppProductCreateRouteImport.update({
  id: '/product/create',
  path: '/product/create',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProductCategoryRoute = AppProductCategoryRouteImport.update({
  id: '/product/category',
  path: '/product/category',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProductIdRoute = AppProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProcurementSuppliersRoute = AppProcurementSuppliersRouteImport.update({
  id: '/procurement/suppliers',
  path: '/procurement/suppliers',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProcurementOrdersRoute = AppProcurementOrdersRouteImport.update({
  id: '/procurement/orders',
  path: '/procurement/orders',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMokaMonitoringRoute = AppMokaMonitoringRouteImport.update({
  id: '/moka/monitoring',
  path: '/moka/monitoring',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMaterialUomRoute = AppMaterialUomRouteImport.update({
  id: '/material/uom',
  path: '/material/uom',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMaterialStockRoute = AppMaterialStockRouteImport.update({
  id: '/material/stock',
  path: '/material/stock',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMaterialLedgerRoute = AppMaterialLedgerRouteImport.update({
  id: '/material/ledger',
  path: '/material/ledger',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMaterialCreateRoute = AppMaterialCreateRouteImport.update({
  id: '/material/create',
  path: '/material/create',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMaterialCategoryRoute = AppMaterialCategoryRouteImport.update({
  id: '/material/category',
  path: '/material/category',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLocationCreateRoute = AppLocationCreateRouteImport.update({
  id: '/location/create',
  path: '/location/create',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppLocationIdRoute = AppLocationIdRouteImport.update({
  id: '/location/$id',
  path: '/location/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInventorySummaryRoute = AppInventorySummaryRouteImport.update({
  id: '/inventory/summary',
  path: '/inventory/summary',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFinanceLedgerArApRoute = AppFinanceLedgerArApRouteImport.update({
  id: '/finance/ledger-ar-ap',
  path: '/finance/ledger-ar-ap',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFinanceLedgerRoute = AppFinanceLedgerRouteImport.update({
  id: '/finance/ledger',
  path: '/finance/ledger',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFinanceExpensesRoute = AppFinanceExpensesRouteImport.update({
  id: '/finance/expenses',
  path: '/finance/expenses',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppFinanceAccountsRoute = AppFinanceAccountsRouteImport.update({
  id: '/finance/accounts',
  path: '/finance/accounts',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppExamplesPageNewRoute = AppExamplesPageNewRouteImport.update({
  id: '/examples/page-new',
  path: '/examples/page-new',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppExamplesFormComponentsRoute =
  AppExamplesFormComponentsRouteImport.update({
    id: '/examples/form-components',
    path: '/examples/form-components',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppExamplesDataTableRoute = AppExamplesDataTableRouteImport.update({
  id: '/examples/data-table',
  path: '/examples/data-table',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAnalyticsStockRoute = AppAnalyticsStockRouteImport.update({
  id: '/analytics/stock',
  path: '/analytics/stock',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppAnalyticsProductionRoute = AppAnalyticsProductionRouteImport.update({
  id: '/analytics/production',
  path: '/analytics/production',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMaterialIdIndexRoute = AppMaterialIdIndexRouteImport.update({
  id: '/material/$id/',
  path: '/material/$id/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInventoryTransactionsIndexRoute =
  AppInventoryTransactionsIndexRouteImport.update({
    id: '/inventory/transactions/',
    path: '/inventory/transactions/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppExamplesSearchIndexRoute = AppExamplesSearchIndexRouteImport.update({
  id: '/examples/search/',
  path: '/examples/search/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppExamplesPageLayoutsIndexRoute =
  AppExamplesPageLayoutsIndexRouteImport.update({
    id: '/examples/page-layouts/',
    path: '/examples/page-layouts/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppExamplesLayoutsIndexRoute = AppExamplesLayoutsIndexRouteImport.update({
  id: '/examples/layouts/',
  path: '/examples/layouts/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppExamplesFormIndexRoute = AppExamplesFormIndexRouteImport.update({
  id: '/examples/form/',
  path: '/examples/form/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppExamplesDialogFormIndexRoute =
  AppExamplesDialogFormIndexRouteImport.update({
    id: '/examples/dialog-form/',
    path: '/examples/dialog-form/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppExamplesDetailsIndexRoute = AppExamplesDetailsIndexRouteImport.update({
  id: '/examples/details/',
  path: '/examples/details/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppExamplesDetailIndexRoute = AppExamplesDetailIndexRouteImport.update({
  id: '/examples/detail/',
  path: '/examples/detail/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppExamplesDashboardIndexRoute =
  AppExamplesDashboardIndexRouteImport.update({
    id: '/examples/dashboard/',
    path: '/examples/dashboard/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppExamplesComplexFormIndexRoute =
  AppExamplesComplexFormIndexRouteImport.update({
    id: '/examples/complex-form/',
    path: '/examples/complex-form/',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppExamplesChartsIndexRoute = AppExamplesChartsIndexRouteImport.update({
  id: '/examples/charts/',
  path: '/examples/charts/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsUserCreateRoute = AppSettingsUserCreateRouteImport.update({
  id: '/settings/user/create',
  path: '/settings/user/create',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsUserIdRoute = AppSettingsUserIdRouteImport.update({
  id: '/settings/user/$id',
  path: '/settings/user/$id',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppSettingsTabUserRoute = AppSettingsTabUserRouteImport.update({
  id: '/user',
  path: '/user',
  getParentRoute: () => AppSettingsTabRoute,
} as any)
const AppSettingsTabRoleRoute = AppSettingsTabRoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => AppSettingsTabRoute,
} as any)
const AppMaterialIdUpdateRoute = AppMaterialIdUpdateRouteImport.update({
  id: '/material/$id/update',
  path: '/material/$id/update',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppMaterialIdRecipeRoute = AppMaterialIdRecipeRouteImport.update({
  id: '/material/$id/recipe',
  path: '/material/$id/recipe',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppInventoryTransactionsTransferRoute =
  AppInventoryTransactionsTransferRouteImport.update({
    id: '/inventory/transactions/transfer',
    path: '/inventory/transactions/transfer',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppInventoryTransactionsAdjustmentRoute =
  AppInventoryTransactionsAdjustmentRouteImport.update({
    id: '/inventory/transactions/adjustment',
    path: '/inventory/transactions/adjustment',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppInventoryTransactionsIdRoute =
  AppInventoryTransactionsIdRouteImport.update({
    id: '/inventory/transactions/$id',
    path: '/inventory/transactions/$id',
    getParentRoute: () => AppRouteRoute,
  } as any)
const AppExamplesLayoutsTwoRoute = AppExamplesLayoutsTwoRouteImport.update({
  id: '/examples/layouts/two',
  path: '/examples/layouts/two',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppExamplesLayoutsOneRoute = AppExamplesLayoutsOneRouteImport.update({
  id: '/examples/layouts/one',
  path: '/examples/layouts/one',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/$': typeof AppSplatRoute
  '/login': typeof AuthLoginRoute
  '/analytics/production': typeof AppAnalyticsProductionRoute
  '/analytics/stock': typeof AppAnalyticsStockRoute
  '/examples/data-table': typeof AppExamplesDataTableRoute
  '/examples/form-components': typeof AppExamplesFormComponentsRoute
  '/examples/page-new': typeof AppExamplesPageNewRoute
  '/finance/accounts': typeof AppFinanceAccountsRoute
  '/finance/expenses': typeof AppFinanceExpensesRoute
  '/finance/ledger': typeof AppFinanceLedgerRoute
  '/finance/ledger-ar-ap': typeof AppFinanceLedgerArApRoute
  '/inventory/summary': typeof AppInventorySummaryRoute
  '/location/$id': typeof AppLocationIdRoute
  '/location/create': typeof AppLocationCreateRoute
  '/material/category': typeof AppMaterialCategoryRoute
  '/material/create': typeof AppMaterialCreateRoute
  '/material/ledger': typeof AppMaterialLedgerRoute
  '/material/stock': typeof AppMaterialStockRoute
  '/material/uom': typeof AppMaterialUomRoute
  '/moka/monitoring': typeof AppMokaMonitoringRoute
  '/procurement/orders': typeof AppProcurementOrdersRoute
  '/procurement/suppliers': typeof AppProcurementSuppliersRoute
  '/product/$id': typeof AppProductIdRoute
  '/product/category': typeof AppProductCategoryRoute
  '/product/create': typeof AppProductCreateRoute
  '/product/sales-type': typeof AppProductSalesTypeRoute
  '/production/work-orders': typeof AppProductionWorkOrdersRoute
  '/sales/customers': typeof AppSalesCustomersRoute
  '/sales/orders': typeof AppSalesOrdersRoute
  '/settings': typeof AppSettingsTabRouteWithChildren
  '/docs/$layer': typeof DocsDocsLayerRoute
  '/location/': typeof AppLocationIndexRoute
  '/material/': typeof AppMaterialIndexRoute
  '/product/': typeof AppProductIndexRoute
  '/docs/': typeof DocsDocsIndexRoute
  '/examples/layouts/one': typeof AppExamplesLayoutsOneRoute
  '/examples/layouts/two': typeof AppExamplesLayoutsTwoRoute
  '/inventory/transactions/$id': typeof AppInventoryTransactionsIdRoute
  '/inventory/transactions/adjustment': typeof AppInventoryTransactionsAdjustmentRoute
  '/inventory/transactions/transfer': typeof AppInventoryTransactionsTransferRoute
  '/material/$id/recipe': typeof AppMaterialIdRecipeRoute
  '/material/$id/update': typeof AppMaterialIdUpdateRoute
  '/settings/role': typeof AppSettingsTabRoleRoute
  '/settings/user': typeof AppSettingsTabUserRoute
  '/settings/user/$id': typeof AppSettingsUserIdRoute
  '/settings/user/create': typeof AppSettingsUserCreateRoute
  '/examples/charts/': typeof AppExamplesChartsIndexRoute
  '/examples/complex-form/': typeof AppExamplesComplexFormIndexRoute
  '/examples/dashboard/': typeof AppExamplesDashboardIndexRoute
  '/examples/detail/': typeof AppExamplesDetailIndexRoute
  '/examples/details/': typeof AppExamplesDetailsIndexRoute
  '/examples/dialog-form/': typeof AppExamplesDialogFormIndexRoute
  '/examples/form/': typeof AppExamplesFormIndexRoute
  '/examples/layouts/': typeof AppExamplesLayoutsIndexRoute
  '/examples/page-layouts/': typeof AppExamplesPageLayoutsIndexRoute
  '/examples/search/': typeof AppExamplesSearchIndexRoute
  '/inventory/transactions/': typeof AppInventoryTransactionsIndexRoute
  '/material/$id/': typeof AppMaterialIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/$': typeof AppSplatRoute
  '/login': typeof AuthLoginRoute
  '/analytics/production': typeof AppAnalyticsProductionRoute
  '/analytics/stock': typeof AppAnalyticsStockRoute
  '/examples/data-table': typeof AppExamplesDataTableRoute
  '/examples/form-components': typeof AppExamplesFormComponentsRoute
  '/examples/page-new': typeof AppExamplesPageNewRoute
  '/finance/accounts': typeof AppFinanceAccountsRoute
  '/finance/expenses': typeof AppFinanceExpensesRoute
  '/finance/ledger': typeof AppFinanceLedgerRoute
  '/finance/ledger-ar-ap': typeof AppFinanceLedgerArApRoute
  '/inventory/summary': typeof AppInventorySummaryRoute
  '/location/$id': typeof AppLocationIdRoute
  '/location/create': typeof AppLocationCreateRoute
  '/material/category': typeof AppMaterialCategoryRoute
  '/material/create': typeof AppMaterialCreateRoute
  '/material/ledger': typeof AppMaterialLedgerRoute
  '/material/stock': typeof AppMaterialStockRoute
  '/material/uom': typeof AppMaterialUomRoute
  '/moka/monitoring': typeof AppMokaMonitoringRoute
  '/procurement/orders': typeof AppProcurementOrdersRoute
  '/procurement/suppliers': typeof AppProcurementSuppliersRoute
  '/product/$id': typeof AppProductIdRoute
  '/product/category': typeof AppProductCategoryRoute
  '/product/create': typeof AppProductCreateRoute
  '/product/sales-type': typeof AppProductSalesTypeRoute
  '/production/work-orders': typeof AppProductionWorkOrdersRoute
  '/sales/customers': typeof AppSalesCustomersRoute
  '/sales/orders': typeof AppSalesOrdersRoute
  '/settings': typeof AppSettingsTabRouteWithChildren
  '/docs/$layer': typeof DocsDocsLayerRoute
  '/location': typeof AppLocationIndexRoute
  '/material': typeof AppMaterialIndexRoute
  '/product': typeof AppProductIndexRoute
  '/docs': typeof DocsDocsIndexRoute
  '/examples/layouts/one': typeof AppExamplesLayoutsOneRoute
  '/examples/layouts/two': typeof AppExamplesLayoutsTwoRoute
  '/inventory/transactions/$id': typeof AppInventoryTransactionsIdRoute
  '/inventory/transactions/adjustment': typeof AppInventoryTransactionsAdjustmentRoute
  '/inventory/transactions/transfer': typeof AppInventoryTransactionsTransferRoute
  '/material/$id/recipe': typeof AppMaterialIdRecipeRoute
  '/material/$id/update': typeof AppMaterialIdUpdateRoute
  '/settings/role': typeof AppSettingsTabRoleRoute
  '/settings/user': typeof AppSettingsTabUserRoute
  '/settings/user/$id': typeof AppSettingsUserIdRoute
  '/settings/user/create': typeof AppSettingsUserCreateRoute
  '/examples/charts': typeof AppExamplesChartsIndexRoute
  '/examples/complex-form': typeof AppExamplesComplexFormIndexRoute
  '/examples/dashboard': typeof AppExamplesDashboardIndexRoute
  '/examples/detail': typeof AppExamplesDetailIndexRoute
  '/examples/details': typeof AppExamplesDetailsIndexRoute
  '/examples/dialog-form': typeof AppExamplesDialogFormIndexRoute
  '/examples/form': typeof AppExamplesFormIndexRoute
  '/examples/layouts': typeof AppExamplesLayoutsIndexRoute
  '/examples/page-layouts': typeof AppExamplesPageLayoutsIndexRoute
  '/examples/search': typeof AppExamplesSearchIndexRoute
  '/inventory/transactions': typeof AppInventoryTransactionsIndexRoute
  '/material/$id': typeof AppMaterialIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteRouteWithChildren
  '/_auth': typeof AuthRouteRouteWithChildren
  '/_docs': typeof DocsRouteWithChildren
  '/_app/$': typeof AppSplatRoute
  '/_auth/login': typeof AuthLoginRoute
  '/_app/': typeof AppIndexRoute
  '/_app/analytics/production': typeof AppAnalyticsProductionRoute
  '/_app/analytics/stock': typeof AppAnalyticsStockRoute
  '/_app/examples/data-table': typeof AppExamplesDataTableRoute
  '/_app/examples/form-components': typeof AppExamplesFormComponentsRoute
  '/_app/examples/page-new': typeof AppExamplesPageNewRoute
  '/_app/finance/accounts': typeof AppFinanceAccountsRoute
  '/_app/finance/expenses': typeof AppFinanceExpensesRoute
  '/_app/finance/ledger': typeof AppFinanceLedgerRoute
  '/_app/finance/ledger-ar-ap': typeof AppFinanceLedgerArApRoute
  '/_app/inventory/summary': typeof AppInventorySummaryRoute
  '/_app/location/$id': typeof AppLocationIdRoute
  '/_app/location/create': typeof AppLocationCreateRoute
  '/_app/material/category': typeof AppMaterialCategoryRoute
  '/_app/material/create': typeof AppMaterialCreateRoute
  '/_app/material/ledger': typeof AppMaterialLedgerRoute
  '/_app/material/stock': typeof AppMaterialStockRoute
  '/_app/material/uom': typeof AppMaterialUomRoute
  '/_app/moka/monitoring': typeof AppMokaMonitoringRoute
  '/_app/procurement/orders': typeof AppProcurementOrdersRoute
  '/_app/procurement/suppliers': typeof AppProcurementSuppliersRoute
  '/_app/product/$id': typeof AppProductIdRoute
  '/_app/product/category': typeof AppProductCategoryRoute
  '/_app/product/create': typeof AppProductCreateRoute
  '/_app/product/sales-type': typeof AppProductSalesTypeRoute
  '/_app/production/work-orders': typeof AppProductionWorkOrdersRoute
  '/_app/sales/customers': typeof AppSalesCustomersRoute
  '/_app/sales/orders': typeof AppSalesOrdersRoute
  '/_app/settings/_tab': typeof AppSettingsTabRouteWithChildren
  '/_docs/docs/$layer': typeof DocsDocsLayerRoute
  '/_app/location/': typeof AppLocationIndexRoute
  '/_app/material/': typeof AppMaterialIndexRoute
  '/_app/product/': typeof AppProductIndexRoute
  '/_docs/docs/': typeof DocsDocsIndexRoute
  '/_app/examples/layouts/one': typeof AppExamplesLayoutsOneRoute
  '/_app/examples/layouts/two': typeof AppExamplesLayoutsTwoRoute
  '/_app/inventory/transactions/$id': typeof AppInventoryTransactionsIdRoute
  '/_app/inventory/transactions/adjustment': typeof AppInventoryTransactionsAdjustmentRoute
  '/_app/inventory/transactions/transfer': typeof AppInventoryTransactionsTransferRoute
  '/_app/material/$id/recipe': typeof AppMaterialIdRecipeRoute
  '/_app/material/$id/update': typeof AppMaterialIdUpdateRoute
  '/_app/settings/_tab/role': typeof AppSettingsTabRoleRoute
  '/_app/settings/_tab/user': typeof AppSettingsTabUserRoute
  '/_app/settings/user/$id': typeof AppSettingsUserIdRoute
  '/_app/settings/user/create': typeof AppSettingsUserCreateRoute
  '/_app/examples/charts/': typeof AppExamplesChartsIndexRoute
  '/_app/examples/complex-form/': typeof AppExamplesComplexFormIndexRoute
  '/_app/examples/dashboard/': typeof AppExamplesDashboardIndexRoute
  '/_app/examples/detail/': typeof AppExamplesDetailIndexRoute
  '/_app/examples/details/': typeof AppExamplesDetailsIndexRoute
  '/_app/examples/dialog-form/': typeof AppExamplesDialogFormIndexRoute
  '/_app/examples/form/': typeof AppExamplesFormIndexRoute
  '/_app/examples/layouts/': typeof AppExamplesLayoutsIndexRoute
  '/_app/examples/page-layouts/': typeof AppExamplesPageLayoutsIndexRoute
  '/_app/examples/search/': typeof AppExamplesSearchIndexRoute
  '/_app/inventory/transactions/': typeof AppInventoryTransactionsIndexRoute
  '/_app/material/$id/': typeof AppMaterialIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$'
    | '/login'
    | '/analytics/production'
    | '/analytics/stock'
    | '/examples/data-table'
    | '/examples/form-components'
    | '/examples/page-new'
    | '/finance/accounts'
    | '/finance/expenses'
    | '/finance/ledger'
    | '/finance/ledger-ar-ap'
    | '/inventory/summary'
    | '/location/$id'
    | '/location/create'
    | '/material/category'
    | '/material/create'
    | '/material/ledger'
    | '/material/stock'
    | '/material/uom'
    | '/moka/monitoring'
    | '/procurement/orders'
    | '/procurement/suppliers'
    | '/product/$id'
    | '/product/category'
    | '/product/create'
    | '/product/sales-type'
    | '/production/work-orders'
    | '/sales/customers'
    | '/sales/orders'
    | '/settings'
    | '/docs/$layer'
    | '/location/'
    | '/material/'
    | '/product/'
    | '/docs/'
    | '/examples/layouts/one'
    | '/examples/layouts/two'
    | '/inventory/transactions/$id'
    | '/inventory/transactions/adjustment'
    | '/inventory/transactions/transfer'
    | '/material/$id/recipe'
    | '/material/$id/update'
    | '/settings/role'
    | '/settings/user'
    | '/settings/user/$id'
    | '/settings/user/create'
    | '/examples/charts/'
    | '/examples/complex-form/'
    | '/examples/dashboard/'
    | '/examples/detail/'
    | '/examples/details/'
    | '/examples/dialog-form/'
    | '/examples/form/'
    | '/examples/layouts/'
    | '/examples/page-layouts/'
    | '/examples/search/'
    | '/inventory/transactions/'
    | '/material/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$'
    | '/login'
    | '/analytics/production'
    | '/analytics/stock'
    | '/examples/data-table'
    | '/examples/form-components'
    | '/examples/page-new'
    | '/finance/accounts'
    | '/finance/expenses'
    | '/finance/ledger'
    | '/finance/ledger-ar-ap'
    | '/inventory/summary'
    | '/location/$id'
    | '/location/create'
    | '/material/category'
    | '/material/create'
    | '/material/ledger'
    | '/material/stock'
    | '/material/uom'
    | '/moka/monitoring'
    | '/procurement/orders'
    | '/procurement/suppliers'
    | '/product/$id'
    | '/product/category'
    | '/product/create'
    | '/product/sales-type'
    | '/production/work-orders'
    | '/sales/customers'
    | '/sales/orders'
    | '/settings'
    | '/docs/$layer'
    | '/location'
    | '/material'
    | '/product'
    | '/docs'
    | '/examples/layouts/one'
    | '/examples/layouts/two'
    | '/inventory/transactions/$id'
    | '/inventory/transactions/adjustment'
    | '/inventory/transactions/transfer'
    | '/material/$id/recipe'
    | '/material/$id/update'
    | '/settings/role'
    | '/settings/user'
    | '/settings/user/$id'
    | '/settings/user/create'
    | '/examples/charts'
    | '/examples/complex-form'
    | '/examples/dashboard'
    | '/examples/detail'
    | '/examples/details'
    | '/examples/dialog-form'
    | '/examples/form'
    | '/examples/layouts'
    | '/examples/page-layouts'
    | '/examples/search'
    | '/inventory/transactions'
    | '/material/$id'
  id:
    | '__root__'
    | '/_app'
    | '/_auth'
    | '/_docs'
    | '/_app/$'
    | '/_auth/login'
    | '/_app/'
    | '/_app/analytics/production'
    | '/_app/analytics/stock'
    | '/_app/examples/data-table'
    | '/_app/examples/form-components'
    | '/_app/examples/page-new'
    | '/_app/finance/accounts'
    | '/_app/finance/expenses'
    | '/_app/finance/ledger'
    | '/_app/finance/ledger-ar-ap'
    | '/_app/inventory/summary'
    | '/_app/location/$id'
    | '/_app/location/create'
    | '/_app/material/category'
    | '/_app/material/create'
    | '/_app/material/ledger'
    | '/_app/material/stock'
    | '/_app/material/uom'
    | '/_app/moka/monitoring'
    | '/_app/procurement/orders'
    | '/_app/procurement/suppliers'
    | '/_app/product/$id'
    | '/_app/product/category'
    | '/_app/product/create'
    | '/_app/product/sales-type'
    | '/_app/production/work-orders'
    | '/_app/sales/customers'
    | '/_app/sales/orders'
    | '/_app/settings/_tab'
    | '/_docs/docs/$layer'
    | '/_app/location/'
    | '/_app/material/'
    | '/_app/product/'
    | '/_docs/docs/'
    | '/_app/examples/layouts/one'
    | '/_app/examples/layouts/two'
    | '/_app/inventory/transactions/$id'
    | '/_app/inventory/transactions/adjustment'
    | '/_app/inventory/transactions/transfer'
    | '/_app/material/$id/recipe'
    | '/_app/material/$id/update'
    | '/_app/settings/_tab/role'
    | '/_app/settings/_tab/user'
    | '/_app/settings/user/$id'
    | '/_app/settings/user/create'
    | '/_app/examples/charts/'
    | '/_app/examples/complex-form/'
    | '/_app/examples/dashboard/'
    | '/_app/examples/detail/'
    | '/_app/examples/details/'
    | '/_app/examples/dialog-form/'
    | '/_app/examples/form/'
    | '/_app/examples/layouts/'
    | '/_app/examples/page-layouts/'
    | '/_app/examples/search/'
    | '/_app/inventory/transactions/'
    | '/_app/material/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRouteRoute: typeof AppRouteRouteWithChildren
  AuthRouteRoute: typeof AuthRouteRouteWithChildren
  DocsRoute: typeof DocsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_docs': {
      id: '/_docs'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_auth/login': {
      id: '/_auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof AuthLoginRouteImport
      parentRoute: typeof AuthRouteRoute
    }
    '/_app/$': {
      id: '/_app/$'
      path: '/$'
      fullPath: '/$'
      preLoaderRoute: typeof AppSplatRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_docs/docs/': {
      id: '/_docs/docs/'
      path: '/docs'
      fullPath: '/docs/'
      preLoaderRoute: typeof DocsDocsIndexRouteImport
      parentRoute: typeof DocsRoute
    }
    '/_app/product/': {
      id: '/_app/product/'
      path: '/product'
      fullPath: '/product/'
      preLoaderRoute: typeof AppProductIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/material/': {
      id: '/_app/material/'
      path: '/material'
      fullPath: '/material/'
      preLoaderRoute: typeof AppMaterialIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/location/': {
      id: '/_app/location/'
      path: '/location'
      fullPath: '/location/'
      preLoaderRoute: typeof AppLocationIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_docs/docs/$layer': {
      id: '/_docs/docs/$layer'
      path: '/docs/$layer'
      fullPath: '/docs/$layer'
      preLoaderRoute: typeof DocsDocsLayerRouteImport
      parentRoute: typeof DocsRoute
    }
    '/_app/settings/_tab': {
      id: '/_app/settings/_tab'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsTabRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/sales/orders': {
      id: '/_app/sales/orders'
      path: '/sales/orders'
      fullPath: '/sales/orders'
      preLoaderRoute: typeof AppSalesOrdersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/sales/customers': {
      id: '/_app/sales/customers'
      path: '/sales/customers'
      fullPath: '/sales/customers'
      preLoaderRoute: typeof AppSalesCustomersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/production/work-orders': {
      id: '/_app/production/work-orders'
      path: '/production/work-orders'
      fullPath: '/production/work-orders'
      preLoaderRoute: typeof AppProductionWorkOrdersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/product/sales-type': {
      id: '/_app/product/sales-type'
      path: '/product/sales-type'
      fullPath: '/product/sales-type'
      preLoaderRoute: typeof AppProductSalesTypeRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/product/create': {
      id: '/_app/product/create'
      path: '/product/create'
      fullPath: '/product/create'
      preLoaderRoute: typeof AppProductCreateRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/product/category': {
      id: '/_app/product/category'
      path: '/product/category'
      fullPath: '/product/category'
      preLoaderRoute: typeof AppProductCategoryRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/product/$id': {
      id: '/_app/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof AppProductIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/procurement/suppliers': {
      id: '/_app/procurement/suppliers'
      path: '/procurement/suppliers'
      fullPath: '/procurement/suppliers'
      preLoaderRoute: typeof AppProcurementSuppliersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/procurement/orders': {
      id: '/_app/procurement/orders'
      path: '/procurement/orders'
      fullPath: '/procurement/orders'
      preLoaderRoute: typeof AppProcurementOrdersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/moka/monitoring': {
      id: '/_app/moka/monitoring'
      path: '/moka/monitoring'
      fullPath: '/moka/monitoring'
      preLoaderRoute: typeof AppMokaMonitoringRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/material/uom': {
      id: '/_app/material/uom'
      path: '/material/uom'
      fullPath: '/material/uom'
      preLoaderRoute: typeof AppMaterialUomRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/material/stock': {
      id: '/_app/material/stock'
      path: '/material/stock'
      fullPath: '/material/stock'
      preLoaderRoute: typeof AppMaterialStockRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/material/ledger': {
      id: '/_app/material/ledger'
      path: '/material/ledger'
      fullPath: '/material/ledger'
      preLoaderRoute: typeof AppMaterialLedgerRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/material/create': {
      id: '/_app/material/create'
      path: '/material/create'
      fullPath: '/material/create'
      preLoaderRoute: typeof AppMaterialCreateRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/material/category': {
      id: '/_app/material/category'
      path: '/material/category'
      fullPath: '/material/category'
      preLoaderRoute: typeof AppMaterialCategoryRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/location/create': {
      id: '/_app/location/create'
      path: '/location/create'
      fullPath: '/location/create'
      preLoaderRoute: typeof AppLocationCreateRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/location/$id': {
      id: '/_app/location/$id'
      path: '/location/$id'
      fullPath: '/location/$id'
      preLoaderRoute: typeof AppLocationIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/inventory/summary': {
      id: '/_app/inventory/summary'
      path: '/inventory/summary'
      fullPath: '/inventory/summary'
      preLoaderRoute: typeof AppInventorySummaryRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/finance/ledger-ar-ap': {
      id: '/_app/finance/ledger-ar-ap'
      path: '/finance/ledger-ar-ap'
      fullPath: '/finance/ledger-ar-ap'
      preLoaderRoute: typeof AppFinanceLedgerArApRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/finance/ledger': {
      id: '/_app/finance/ledger'
      path: '/finance/ledger'
      fullPath: '/finance/ledger'
      preLoaderRoute: typeof AppFinanceLedgerRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/finance/expenses': {
      id: '/_app/finance/expenses'
      path: '/finance/expenses'
      fullPath: '/finance/expenses'
      preLoaderRoute: typeof AppFinanceExpensesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/finance/accounts': {
      id: '/_app/finance/accounts'
      path: '/finance/accounts'
      fullPath: '/finance/accounts'
      preLoaderRoute: typeof AppFinanceAccountsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/examples/page-new': {
      id: '/_app/examples/page-new'
      path: '/examples/page-new'
      fullPath: '/examples/page-new'
      preLoaderRoute: typeof AppExamplesPageNewRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/examples/form-components': {
      id: '/_app/examples/form-components'
      path: '/examples/form-components'
      fullPath: '/examples/form-components'
      preLoaderRoute: typeof AppExamplesFormComponentsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/examples/data-table': {
      id: '/_app/examples/data-table'
      path: '/examples/data-table'
      fullPath: '/examples/data-table'
      preLoaderRoute: typeof AppExamplesDataTableRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/analytics/stock': {
      id: '/_app/analytics/stock'
      path: '/analytics/stock'
      fullPath: '/analytics/stock'
      preLoaderRoute: typeof AppAnalyticsStockRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/analytics/production': {
      id: '/_app/analytics/production'
      path: '/analytics/production'
      fullPath: '/analytics/production'
      preLoaderRoute: typeof AppAnalyticsProductionRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/material/$id/': {
      id: '/_app/material/$id/'
      path: '/material/$id'
      fullPath: '/material/$id/'
      preLoaderRoute: typeof AppMaterialIdIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/inventory/transactions/': {
      id: '/_app/inventory/transactions/'
      path: '/inventory/transactions'
      fullPath: '/inventory/transactions/'
      preLoaderRoute: typeof AppInventoryTransactionsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/examples/search/': {
      id: '/_app/examples/search/'
      path: '/examples/search'
      fullPath: '/examples/search/'
      preLoaderRoute: typeof AppExamplesSearchIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/examples/page-layouts/': {
      id: '/_app/examples/page-layouts/'
      path: '/examples/page-layouts'
      fullPath: '/examples/page-layouts/'
      preLoaderRoute: typeof AppExamplesPageLayoutsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/examples/layouts/': {
      id: '/_app/examples/layouts/'
      path: '/examples/layouts'
      fullPath: '/examples/layouts/'
      preLoaderRoute: typeof AppExamplesLayoutsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/examples/form/': {
      id: '/_app/examples/form/'
      path: '/examples/form'
      fullPath: '/examples/form/'
      preLoaderRoute: typeof AppExamplesFormIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/examples/dialog-form/': {
      id: '/_app/examples/dialog-form/'
      path: '/examples/dialog-form'
      fullPath: '/examples/dialog-form/'
      preLoaderRoute: typeof AppExamplesDialogFormIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/examples/details/': {
      id: '/_app/examples/details/'
      path: '/examples/details'
      fullPath: '/examples/details/'
      preLoaderRoute: typeof AppExamplesDetailsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/examples/detail/': {
      id: '/_app/examples/detail/'
      path: '/examples/detail'
      fullPath: '/examples/detail/'
      preLoaderRoute: typeof AppExamplesDetailIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/examples/dashboard/': {
      id: '/_app/examples/dashboard/'
      path: '/examples/dashboard'
      fullPath: '/examples/dashboard/'
      preLoaderRoute: typeof AppExamplesDashboardIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/examples/complex-form/': {
      id: '/_app/examples/complex-form/'
      path: '/examples/complex-form'
      fullPath: '/examples/complex-form/'
      preLoaderRoute: typeof AppExamplesComplexFormIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/examples/charts/': {
      id: '/_app/examples/charts/'
      path: '/examples/charts'
      fullPath: '/examples/charts/'
      preLoaderRoute: typeof AppExamplesChartsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings/user/create': {
      id: '/_app/settings/user/create'
      path: '/settings/user/create'
      fullPath: '/settings/user/create'
      preLoaderRoute: typeof AppSettingsUserCreateRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings/user/$id': {
      id: '/_app/settings/user/$id'
      path: '/settings/user/$id'
      fullPath: '/settings/user/$id'
      preLoaderRoute: typeof AppSettingsUserIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/settings/_tab/user': {
      id: '/_app/settings/_tab/user'
      path: '/user'
      fullPath: '/settings/user'
      preLoaderRoute: typeof AppSettingsTabUserRouteImport
      parentRoute: typeof AppSettingsTabRoute
    }
    '/_app/settings/_tab/role': {
      id: '/_app/settings/_tab/role'
      path: '/role'
      fullPath: '/settings/role'
      preLoaderRoute: typeof AppSettingsTabRoleRouteImport
      parentRoute: typeof AppSettingsTabRoute
    }
    '/_app/material/$id/update': {
      id: '/_app/material/$id/update'
      path: '/material/$id/update'
      fullPath: '/material/$id/update'
      preLoaderRoute: typeof AppMaterialIdUpdateRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/material/$id/recipe': {
      id: '/_app/material/$id/recipe'
      path: '/material/$id/recipe'
      fullPath: '/material/$id/recipe'
      preLoaderRoute: typeof AppMaterialIdRecipeRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/inventory/transactions/transfer': {
      id: '/_app/inventory/transactions/transfer'
      path: '/inventory/transactions/transfer'
      fullPath: '/inventory/transactions/transfer'
      preLoaderRoute: typeof AppInventoryTransactionsTransferRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/inventory/transactions/adjustment': {
      id: '/_app/inventory/transactions/adjustment'
      path: '/inventory/transactions/adjustment'
      fullPath: '/inventory/transactions/adjustment'
      preLoaderRoute: typeof AppInventoryTransactionsAdjustmentRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/inventory/transactions/$id': {
      id: '/_app/inventory/transactions/$id'
      path: '/inventory/transactions/$id'
      fullPath: '/inventory/transactions/$id'
      preLoaderRoute: typeof AppInventoryTransactionsIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/examples/layouts/two': {
      id: '/_app/examples/layouts/two'
      path: '/examples/layouts/two'
      fullPath: '/examples/layouts/two'
      preLoaderRoute: typeof AppExamplesLayoutsTwoRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/_app/examples/layouts/one': {
      id: '/_app/examples/layouts/one'
      path: '/examples/layouts/one'
      fullPath: '/examples/layouts/one'
      preLoaderRoute: typeof AppExamplesLayoutsOneRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppSettingsTabRouteChildren {
  AppSettingsTabRoleRoute: typeof AppSettingsTabRoleRoute
  AppSettingsTabUserRoute: typeof AppSettingsTabUserRoute
}

const AppSettingsTabRouteChildren: AppSettingsTabRouteChildren = {
  AppSettingsTabRoleRoute: AppSettingsTabRoleRoute,
  AppSettingsTabUserRoute: AppSettingsTabUserRoute,
}

const AppSettingsTabRouteWithChildren = AppSettingsTabRoute._addFileChildren(
  AppSettingsTabRouteChildren,
)

interface AppRouteRouteChildren {
  AppSplatRoute: typeof AppSplatRoute
  AppIndexRoute: typeof AppIndexRoute
  AppAnalyticsProductionRoute: typeof AppAnalyticsProductionRoute
  AppAnalyticsStockRoute: typeof AppAnalyticsStockRoute
  AppExamplesDataTableRoute: typeof AppExamplesDataTableRoute
  AppExamplesFormComponentsRoute: typeof AppExamplesFormComponentsRoute
  AppExamplesPageNewRoute: typeof AppExamplesPageNewRoute
  AppFinanceAccountsRoute: typeof AppFinanceAccountsRoute
  AppFinanceExpensesRoute: typeof AppFinanceExpensesRoute
  AppFinanceLedgerRoute: typeof AppFinanceLedgerRoute
  AppFinanceLedgerArApRoute: typeof AppFinanceLedgerArApRoute
  AppInventorySummaryRoute: typeof AppInventorySummaryRoute
  AppLocationIdRoute: typeof AppLocationIdRoute
  AppLocationCreateRoute: typeof AppLocationCreateRoute
  AppMaterialCategoryRoute: typeof AppMaterialCategoryRoute
  AppMaterialCreateRoute: typeof AppMaterialCreateRoute
  AppMaterialLedgerRoute: typeof AppMaterialLedgerRoute
  AppMaterialStockRoute: typeof AppMaterialStockRoute
  AppMaterialUomRoute: typeof AppMaterialUomRoute
  AppMokaMonitoringRoute: typeof AppMokaMonitoringRoute
  AppProcurementOrdersRoute: typeof AppProcurementOrdersRoute
  AppProcurementSuppliersRoute: typeof AppProcurementSuppliersRoute
  AppProductIdRoute: typeof AppProductIdRoute
  AppProductCategoryRoute: typeof AppProductCategoryRoute
  AppProductCreateRoute: typeof AppProductCreateRoute
  AppProductSalesTypeRoute: typeof AppProductSalesTypeRoute
  AppProductionWorkOrdersRoute: typeof AppProductionWorkOrdersRoute
  AppSalesCustomersRoute: typeof AppSalesCustomersRoute
  AppSalesOrdersRoute: typeof AppSalesOrdersRoute
  AppSettingsTabRoute: typeof AppSettingsTabRouteWithChildren
  AppLocationIndexRoute: typeof AppLocationIndexRoute
  AppMaterialIndexRoute: typeof AppMaterialIndexRoute
  AppProductIndexRoute: typeof AppProductIndexRoute
  AppExamplesLayoutsOneRoute: typeof AppExamplesLayoutsOneRoute
  AppExamplesLayoutsTwoRoute: typeof AppExamplesLayoutsTwoRoute
  AppInventoryTransactionsIdRoute: typeof AppInventoryTransactionsIdRoute
  AppInventoryTransactionsAdjustmentRoute: typeof AppInventoryTransactionsAdjustmentRoute
  AppInventoryTransactionsTransferRoute: typeof AppInventoryTransactionsTransferRoute
  AppMaterialIdRecipeRoute: typeof AppMaterialIdRecipeRoute
  AppMaterialIdUpdateRoute: typeof AppMaterialIdUpdateRoute
  AppSettingsUserIdRoute: typeof AppSettingsUserIdRoute
  AppSettingsUserCreateRoute: typeof AppSettingsUserCreateRoute
  AppExamplesChartsIndexRoute: typeof AppExamplesChartsIndexRoute
  AppExamplesComplexFormIndexRoute: typeof AppExamplesComplexFormIndexRoute
  AppExamplesDashboardIndexRoute: typeof AppExamplesDashboardIndexRoute
  AppExamplesDetailIndexRoute: typeof AppExamplesDetailIndexRoute
  AppExamplesDetailsIndexRoute: typeof AppExamplesDetailsIndexRoute
  AppExamplesDialogFormIndexRoute: typeof AppExamplesDialogFormIndexRoute
  AppExamplesFormIndexRoute: typeof AppExamplesFormIndexRoute
  AppExamplesLayoutsIndexRoute: typeof AppExamplesLayoutsIndexRoute
  AppExamplesPageLayoutsIndexRoute: typeof AppExamplesPageLayoutsIndexRoute
  AppExamplesSearchIndexRoute: typeof AppExamplesSearchIndexRoute
  AppInventoryTransactionsIndexRoute: typeof AppInventoryTransactionsIndexRoute
  AppMaterialIdIndexRoute: typeof AppMaterialIdIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppSplatRoute: AppSplatRoute,
  AppIndexRoute: AppIndexRoute,
  AppAnalyticsProductionRoute: AppAnalyticsProductionRoute,
  AppAnalyticsStockRoute: AppAnalyticsStockRoute,
  AppExamplesDataTableRoute: AppExamplesDataTableRoute,
  AppExamplesFormComponentsRoute: AppExamplesFormComponentsRoute,
  AppExamplesPageNewRoute: AppExamplesPageNewRoute,
  AppFinanceAccountsRoute: AppFinanceAccountsRoute,
  AppFinanceExpensesRoute: AppFinanceExpensesRoute,
  AppFinanceLedgerRoute: AppFinanceLedgerRoute,
  AppFinanceLedgerArApRoute: AppFinanceLedgerArApRoute,
  AppInventorySummaryRoute: AppInventorySummaryRoute,
  AppLocationIdRoute: AppLocationIdRoute,
  AppLocationCreateRoute: AppLocationCreateRoute,
  AppMaterialCategoryRoute: AppMaterialCategoryRoute,
  AppMaterialCreateRoute: AppMaterialCreateRoute,
  AppMaterialLedgerRoute: AppMaterialLedgerRoute,
  AppMaterialStockRoute: AppMaterialStockRoute,
  AppMaterialUomRoute: AppMaterialUomRoute,
  AppMokaMonitoringRoute: AppMokaMonitoringRoute,
  AppProcurementOrdersRoute: AppProcurementOrdersRoute,
  AppProcurementSuppliersRoute: AppProcurementSuppliersRoute,
  AppProductIdRoute: AppProductIdRoute,
  AppProductCategoryRoute: AppProductCategoryRoute,
  AppProductCreateRoute: AppProductCreateRoute,
  AppProductSalesTypeRoute: AppProductSalesTypeRoute,
  AppProductionWorkOrdersRoute: AppProductionWorkOrdersRoute,
  AppSalesCustomersRoute: AppSalesCustomersRoute,
  AppSalesOrdersRoute: AppSalesOrdersRoute,
  AppSettingsTabRoute: AppSettingsTabRouteWithChildren,
  AppLocationIndexRoute: AppLocationIndexRoute,
  AppMaterialIndexRoute: AppMaterialIndexRoute,
  AppProductIndexRoute: AppProductIndexRoute,
  AppExamplesLayoutsOneRoute: AppExamplesLayoutsOneRoute,
  AppExamplesLayoutsTwoRoute: AppExamplesLayoutsTwoRoute,
  AppInventoryTransactionsIdRoute: AppInventoryTransactionsIdRoute,
  AppInventoryTransactionsAdjustmentRoute:
    AppInventoryTransactionsAdjustmentRoute,
  AppInventoryTransactionsTransferRoute: AppInventoryTransactionsTransferRoute,
  AppMaterialIdRecipeRoute: AppMaterialIdRecipeRoute,
  AppMaterialIdUpdateRoute: AppMaterialIdUpdateRoute,
  AppSettingsUserIdRoute: AppSettingsUserIdRoute,
  AppSettingsUserCreateRoute: AppSettingsUserCreateRoute,
  AppExamplesChartsIndexRoute: AppExamplesChartsIndexRoute,
  AppExamplesComplexFormIndexRoute: AppExamplesComplexFormIndexRoute,
  AppExamplesDashboardIndexRoute: AppExamplesDashboardIndexRoute,
  AppExamplesDetailIndexRoute: AppExamplesDetailIndexRoute,
  AppExamplesDetailsIndexRoute: AppExamplesDetailsIndexRoute,
  AppExamplesDialogFormIndexRoute: AppExamplesDialogFormIndexRoute,
  AppExamplesFormIndexRoute: AppExamplesFormIndexRoute,
  AppExamplesLayoutsIndexRoute: AppExamplesLayoutsIndexRoute,
  AppExamplesPageLayoutsIndexRoute: AppExamplesPageLayoutsIndexRoute,
  AppExamplesSearchIndexRoute: AppExamplesSearchIndexRoute,
  AppInventoryTransactionsIndexRoute: AppInventoryTransactionsIndexRoute,
  AppMaterialIdIndexRoute: AppMaterialIdIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

interface AuthRouteRouteChildren {
  AuthLoginRoute: typeof AuthLoginRoute
}

const AuthRouteRouteChildren: AuthRouteRouteChildren = {
  AuthLoginRoute: AuthLoginRoute,
}

const AuthRouteRouteWithChildren = AuthRouteRoute._addFileChildren(
  AuthRouteRouteChildren,
)

interface DocsRouteChildren {
  DocsDocsLayerRoute: typeof DocsDocsLayerRoute
  DocsDocsIndexRoute: typeof DocsDocsIndexRoute
}

const DocsRouteChildren: DocsRouteChildren = {
  DocsDocsLayerRoute: DocsDocsLayerRoute,
  DocsDocsIndexRoute: DocsDocsIndexRoute,
}

const DocsRouteWithChildren = DocsRoute._addFileChildren(DocsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRouteRoute: AppRouteRouteWithChildren,
  AuthRouteRoute: AuthRouteRouteWithChildren,
  DocsRoute: DocsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
