// AUTO-GENERATED by scripts/generate-web.ts — DO NOT EDIT.
import { z } from 'zod'

import { zc, zp, zq } from '@/lib/validation'

/** RecordId for endpoints that need it (e.g., detail/remove) */
export const RecordId = zc.RecordId

/** Customer loyalty tier levels */
export const CustomerTierEnum = z.enum(['bronze', 'silver', 'gold', 'platinum'])
export type CustomerTier = z.infer<typeof CustomerTierEnum>

/** Loyalty transaction types */
export const LoyaltyTransactionTypeEnum = z.enum(['earned', 'redeemed', 'adjusted', 'expired'])
export type LoyaltyTransactionType = z.infer<typeof LoyaltyTransactionTypeEnum>

export const CustomerDto = z.object({
	id: zp.id,
	code: zp.str,
	name: zp.str,
	email: zp.strNullable,
	phone: zp.strNullable,
	address: zp.strNullable,
	taxId: zp.strNullable,
	dateOfBirth: zp.date.nullable(),
	tier: CustomerTierEnum,
	pointsBalance: zp.id,
	totalPointsEarned: zp.id,
	registeredAt: zp.date,
	lastVisitAt: zp.date.nullable(),
	...zc.AuditBasic.shape,
})
export type CustomerDto = z.infer<typeof CustomerDto>

const CustomerMutationDto = z.object({
	code: zc.strTrim.transform((v) => v.toUpperCase()).pipe(z.string().min(3).max(20)),
	name: zc.strTrim.min(2).max(100),
	email: zc.email.optional().or(z.literal('')),
	phone: zc.strTrim.min(10).max(20).optional().or(z.literal('')),
	address: zc.strTrim.min(5).max(255).optional().or(z.literal('')),
	taxId: zc.strTrim.min(10).max(30).optional().or(z.literal('')),
	dateOfBirth: zp.date.optional(),
})

export const CustomerCreateDto = CustomerMutationDto
export type CustomerCreateDto = z.infer<typeof CustomerCreateDto>

export const CustomerUpdateDto = z.object({
	...RecordId.shape,
	name: zc.strTrim.min(2).max(100).optional(),
	email: zc.email.optional().or(z.literal('')),
	phone: zc.strTrim.min(10).max(20).optional().or(z.literal('')),
	address: zc.strTrim.min(5).max(255).optional().or(z.literal('')),
	taxId: zc.strTrim.min(10).max(30).optional().or(z.literal('')),
	dateOfBirth: zp.date.optional(),
	tier: CustomerTierEnum.optional(),
})
export type CustomerUpdateDto = z.infer<typeof CustomerUpdateDto>

export const CustomerFilterDto = z.object({
	q: zq.search,
	tier: CustomerTierEnum.optional(),
	phone: zc.strTrim.optional(),
	...zq.pagination.shape,
})
export type CustomerFilterDto = z.infer<typeof CustomerFilterDto>

export const CustomerLoyaltyTransactionDto = z.object({
	id: zp.id,
	customerId: zp.id,
	type: LoyaltyTransactionTypeEnum,
	points: zp.id,
	balanceAfter: zp.id,
	referenceType: zp.strNullable,
	referenceId: zp.id.nullable(),
	description: zp.strNullable,
	...zc.AuditBasic.shape,
})
export type CustomerLoyaltyTransactionDto = z.infer<typeof CustomerLoyaltyTransactionDto>

export const CustomerAddPointsDto = z.object({
	customerId: zp.id,
	points: zp.id.min(1).max(100000),
	description: zc.strTrim.min(5).max(255),
	referenceType: zp.str.optional(),
	referenceId: zp.id.optional(),
})
export type CustomerAddPointsDto = z.infer<typeof CustomerAddPointsDto>

export const CustomerRedeemPointsDto = z.object({
	customerId: zp.id,
	points: zp.id.min(1).max(100000),
	description: zc.strTrim.min(5).max(255),
	referenceType: zp.str.optional(),
	referenceId: zp.id.optional(),
})
export type CustomerRedeemPointsDto = z.infer<typeof CustomerRedeemPointsDto>

export const CustomerGetByPhoneDto = z.object({
	phone: zc.strTrim.min(10).max(20),
})
export type CustomerGetByPhoneDto = z.infer<typeof CustomerGetByPhoneDto>
