// AUTO-GENERATED by scripts/generate-web.ts — DO NOT EDIT.

import { createPaginatedResponseSchema, createSuccessResponseSchema } from '@/lib/validation'

import { endpoint } from '@/config/endpoint.gen'

import { apiFactory, createQueryKeys } from '@/lib/api'
import { z } from 'zod'

import { CustomerAddPointsDto, CustomerCreateDto, CustomerDto, CustomerFilterDto, CustomerGetByPhoneDto, CustomerLoyaltyTransactionDto, CustomerUpdateDto, RecordId } from './crm.dto'

const customerKeys = createQueryKeys('crm', 'customer')

export const customerApi = {
	list: apiFactory({ method: 'get', url: endpoint['crm']['list'], params: CustomerFilterDto, result: createPaginatedResponseSchema(CustomerDto), queryKey: customerKeys.list }),
	detail: apiFactory({ method: 'get', url: endpoint['crm']['detail'], params: RecordId, result: createSuccessResponseSchema(CustomerDto), queryKey: (params) => customerKeys.detail(params?.id) }),
	byPhone: apiFactory({ method: 'post', url: endpoint['crm']['byPhone'], body: CustomerGetByPhoneDto, result: createSuccessResponseSchema(CustomerDto), invalidates: [customerKeys.lists()] }),
	create: apiFactory({ method: 'post', url: endpoint['crm']['create'], body: CustomerCreateDto, result: createSuccessResponseSchema(RecordId), invalidates: [customerKeys.lists()] }),
	update: apiFactory({ method: 'patch', url: endpoint['crm']['update'], body: CustomerUpdateDto, result: createSuccessResponseSchema(RecordId), invalidates: [customerKeys.lists()] }),
	remove: apiFactory({ method: 'delete', url: endpoint['crm']['remove'], params: RecordId, result: createSuccessResponseSchema(RecordId), invalidates: [customerKeys.lists()] }),
	addPoints: apiFactory({ method: 'post', url: endpoint['crm']['addPoints'], body: CustomerAddPointsDto, result: createSuccessResponseSchema(RecordId), invalidates: [customerKeys.lists()] }),
	redeemPoints: apiFactory({ method: 'post', url: endpoint['crm']['redeemPoints'], body: CustomerAddPointsDto, result: createSuccessResponseSchema(RecordId), invalidates: [customerKeys.lists()] }),
	loyaltyHistory: apiFactory({ method: 'get', url: endpoint['crm']['loyaltyHistory'], params: RecordId, result: createSuccessResponseSchema(z.array(CustomerLoyaltyTransactionDto)) }),
}
