// AUTO-GENERATED by scripts/generate-web.ts — DO NOT EDIT.

import { createSuccessResponseSchema } from '@/lib/validation'

import { endpoint } from '@/config/endpoint.gen'

import { apiFactory, createQueryKeys } from '@/lib/api'

import { AuthLoginDto, AuthOutputDto, UserDto } from './auth.dto'

const authKeys = createQueryKeys('auth', 'auth')

export const authApi = {
	login: apiFactory({ method: 'post', url: endpoint.auth.login, body: AuthLoginDto, result: createSuccessResponseSchema(AuthOutputDto), invalidates: [authKeys.lists()] }),
	me: apiFactory({ method: 'get', url: endpoint.auth.me, result: createSuccessResponseSchema(UserDto) }),
}
