// AUTO-GENERATED by scripts/generate-web.ts — DO NOT EDIT.
import z from 'zod'
import { UserDetailDto } from '@/features/iam'
import { zc, zp } from '@/lib/validation'

export { UserDetailDto } from '@/features/iam'

export const AuthLoginDto = z.object({
	identifier: zc.strTrim.min(1),
	password: zc.password,
})
export type AuthLoginDto = z.infer<typeof AuthLoginDto>

export const AuthOutputDto = z.object({
	user: UserDetailDto,
	token: zp.str,
})
export type AuthOutputDto = z.infer<typeof AuthOutputDto>
