import { pgEnum, timestamp, uuid } from 'drizzle-orm/pg-core'

// ─── Reusable Column Helpers ──────────────────────────────────────────────────

/**
 * Primary key column using UUIDv4 (generated by default).
 * The app can also supply its own if needed.
 */
export const pk = {
  id: uuid().primaryKey().defaultRandom(),
} as const

/**
 * Audit metadata columns shared by every domain table.
 *
 * - `createdAt` / `updatedAt` are managed by the service layer, not DB triggers,
 *   so they are NOT auto-updated — this keeps the behavior predictable and testable.
 * - `createdBy` / `updatedBy` store UUIDs referencing users.
 *   We intentionally do NOT declare FK here to avoid circular imports.
 *   Referential integrity is enforced at the application layer.
 * - `syncAt` is nullable; only used for data synchronization tracking.
 */
export const metadata = {
  createdAt: timestamp({ mode: 'date', withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp({ mode: 'date', withTimezone: true }).notNull().defaultNow(),
  createdBy: uuid().notNull(),
  updatedBy: uuid().notNull(),
  syncAt: timestamp({ mode: 'date', withTimezone: true }),
} as const

// ─── Shared Enums ─────────────────────────────────────────────────────────────

export const locationTypeEnum = pgEnum('location_type', ['store', 'warehouse'])

export const materialTypeEnum = pgEnum('material_type', ['raw', 'semi'])

export const transactionTypeEnum = pgEnum('transaction_type', [
  'purchase',
  'transfer_in',
  'transfer_out',
  'adjustment',
  'sell',
])
