// AUTO-GENERATED by scripts/generate-web.ts — DO NOT EDIT.
import z from 'zod'
import { LocationDto } from '@/features/location'
import { zc, zp, zq } from '@/lib/validation'

export { LocationDto } from '@/features/location'

/* --------------------------------- ENTITY --------------------------------- */

export const RoleDto = z.object({
	id: zp.id,
	code: zp.str,
	name: zp.str,
	description: zp.str.nullable(),
	permissions: z.array(zp.str),
	isSystem: zp.bool,
	...zc.AuditBasic.shape,
})
export type RoleDto = z.infer<typeof RoleDto>

/* ---------------------------------- HTTP ---------------------------------- */

export const RoleFilterDto = z.object({
	...zq.pagination.shape,
	q: zq.search,
})
export type RoleFilterDto = z.infer<typeof RoleFilterDto>

const RoleMutationDto = z.object({
	code: zc.strTrim.min(2).max(32).toUpperCase(),
	name: zc.strTrim.min(2),
	description: zc.strTrimNullable,
	permissions: z.array(zp.str).default([]),
	isSystem: zp.bool.default(false),
})

export const RoleCreateDto = RoleMutationDto
export type RoleCreateDto = z.infer<typeof RoleCreateDto>

export const RoleUpdateDto = z.object({
	id: zp.id,
	...RoleMutationDto.shape,
})
export type RoleUpdateDto = z.infer<typeof RoleUpdateDto>

/* --------------------------------- ENTITY --------------------------------- */

export const UserDto = z.object({
	id: zp.id,
	email: zp.str,
	username: zp.str,
	fullname: zp.str,
	pinCode: zp.str.nullable(),
	isRoot: zp.bool,
	isSystem: zp.bool,
	isActive: zp.bool,
	defaultLocationId: zp.id.nullable(),
	...zc.AuditBasic.shape,
})
export type UserDto = z.infer<typeof UserDto>

export const UserWithPasswordDto = z.object({
	...UserDto.shape,
	passwordHash: zp.str.nullable(),
})
export type UserWithPasswordDto = z.infer<typeof UserWithPasswordDto>

/* ---------------------------------- HTTP ---------------------------------- */

const UserMutationDto = z.object({
	email: zc.email,
	username: zc.username,
	fullname: zc.fullname,
	pinCode: zp.strNullable,
	isActive: zp.bool.default(true),
	isRoot: zp.bool.default(false),
	defaultLocationId: zp.id.nullable(),
	assignments: z.array(
		z.object({
			locationId: zp.id,
			roleId: zp.id,
		}),
	),
})

export const UserCreateDto = z.object({
	...UserMutationDto.shape,
	password: zc.password,
})
export type UserCreateDto = z.infer<typeof UserCreateDto>

export const UserUpdateDto = z.object({
	...zc.RecordId.shape,
	...UserMutationDto.shape,
	password: zc.password.optional(),
})
export type UserUpdateDto = z.infer<typeof UserUpdateDto>

/* -------------------------------- PASSWORD -------------------------------- */

export const UserChangePasswordDto = z.object({
	oldPassword: zc.password,
	newPassword: zc.password,
})
export type UserChangePasswordDto = z.infer<typeof UserChangePasswordDto>

export const UserAdminUpdatePasswordDto = z.object({
	...zc.RecordId.shape,
	password: zc.password,
})
export type UserAdminUpdatePasswordDto = z.infer<typeof UserAdminUpdatePasswordDto>

/* --------------------------------- ENTITY --------------------------------- */

export const UserAssignmentDto = z.object({
	id: zp.id,
	userId: zp.id,
	roleId: zp.id,
	locationId: zp.id,
	addedAt: zp.date,
	addedBy: zp.id.nullable(),
})
export type UserAssignmentDto = z.infer<typeof UserAssignmentDto>

const UserAssignmentWithRelationsDto = z.object({
	...UserAssignmentDto.shape,
	role: RoleDto,
	location: LocationDto,
})

export const UserDetailDto = z.object({
	...UserDto.shape,
	assignments: z.array(UserAssignmentWithRelationsDto),
})
export type UserDetailDto = z.infer<typeof UserDetailDto>

/* --------------------------------- FILTER --------------------------------- */

export const UserFilterDto = z.object({
	...zq.pagination.shape,
	q: zq.search,
	isActive: zq.boolean.optional(),
	isRoot: zq.boolean.optional(),
	locationId: zq.id.optional(),
})
export type UserFilterDto = z.infer<typeof UserFilterDto>
