// AUTO-GENERATED by scripts/generate-web.ts — DO NOT EDIT.

import { endpoint } from '@/config/endpoint.gen'

import { apiFactory, createQueryKeys } from '@/lib/api'
import { createSuccessResponseSchema } from '@/lib/validation'

import {
	CompanySettingsCreateDto,
	CompanySettingsDto,
	CompanySettingsUpdateDto,
	RecordId,
} from './company.dto'

const companySettingsKeys = createQueryKeys('company', 'company-settings')

export const companySettingsApi = {
	detail: apiFactory({
		method: 'get',
		url: endpoint['company']['detail'],
		params: RecordId,
		result: createSuccessResponseSchema(CompanySettingsDto),
		queryKey: (params) => companySettingsKeys.detail(params?.id),
	}),
	create: apiFactory({
		method: 'post',
		url: endpoint['company']['create'],
		body: CompanySettingsCreateDto,
		result: createSuccessResponseSchema(RecordId),
		invalidates: [companySettingsKeys.lists()],
	}),
	update: apiFactory({
		method: 'patch',
		url: endpoint['company']['update'],
		body: CompanySettingsUpdateDto,
		result: createSuccessResponseSchema(RecordId),
		invalidates: [companySettingsKeys.lists()],
	}),
}
