// AUTO-GENERATED by scripts/generate-web.ts — DO NOT EDIT.

import { endpoint } from '@/config/endpoint.gen'

import { apiFactory, createQueryKeys } from '@/lib/api'
import { createPaginatedResponseSchema, createSuccessResponseSchema, zc } from '@/lib/validation'

import {
	SupplierCreateDto,
	SupplierDto,
	SupplierFilterDto,
	SupplierUpdateDto,
} from './supplier.dto'

const supplierKeys = createQueryKeys('supplier', 'supplier')

export const supplierApi = {
	list: apiFactory({
		method: 'get',
		url: endpoint['supplier']['list'],
		params: SupplierFilterDto,
		result: createPaginatedResponseSchema(SupplierDto),
		queryKey: supplierKeys.list,
	}),
	detail: apiFactory({
		method: 'get',
		url: endpoint['supplier']['detail'],
		params: zc.RecordId,
		result: createSuccessResponseSchema(SupplierDto),
		queryKey: (params) => supplierKeys.detail(params?.id),
	}),
	create: apiFactory({
		method: 'post',
		url: endpoint['supplier']['create'],
		body: SupplierCreateDto,
		result: createSuccessResponseSchema(zc.RecordId),
		invalidates: [supplierKeys.lists()],
	}),
	update: apiFactory({
		method: 'put',
		url: endpoint['supplier']['update'],
		body: SupplierUpdateDto,
		result: createSuccessResponseSchema(zc.RecordId),
		invalidates: [supplierKeys.lists()],
	}),
	remove: apiFactory({
		method: 'delete',
		url: endpoint['supplier']['remove'],
		body: zc.RecordId,
		result: createSuccessResponseSchema(zc.RecordId),
		invalidates: [supplierKeys.lists()],
	}),
}
