// AUTO-GENERATED by scripts/generate-web.ts — DO NOT EDIT.

/** Generated endpoint URL map. Do not edit by hand. */
export const endpoint = {
	auth: {
		login: 'auth/login',
		me: 'auth/me',
	},
	location: {
		list: 'location/list',
		detail: 'location/detail',
		create: 'location/create',
		update: 'location/update',
		remove: 'location/remove',
	},
} as const
