export const SEED_CONFIG = {
	USER_OWNER_EMAIL: Bun.env.SEED_OWNER_EMAIL ?? 'admin@ikki.com',
	USER_OWNER_PASSWORD: Bun.env.SEED_OWNER_PASSWORD ?? 'admin12345',
	USER_OWNER_USERNAME: Bun.env.SEED_OWNER_USERNAME ?? 'admin',

	LOCATIONS: [
		{ code: 'S-IC', name: 'Ikki Coffee', type: 'store' },
		{ code: 'S-IR', name: 'Ikki Resto', type: 'store' },
		{ code: 'W-RUMAH', name: 'Gudang Rumah', type: 'warehouse' },
	],

	SALES_TYPES: [
		{ code: 'DINE_IN', name: 'Dine In', isSystem: true },
		{ code: 'TAKE_AWAY', name: 'Take Away', isSystem: true },
	],
	UOMS: [
		{ code: 'PCS' },
		{ code: 'BOX' },
		{ code: 'PACK' },
		{ code: 'KG' },
		{ code: 'GR' },
		{ code: 'L' },
		{ code: 'ML' },
		{ code: 'M' },
		{ code: 'CM' },
		{ code: 'BUAH' },
		{ code: 'IKAT' },
		{ code: 'SACHET' },
		{ code: 'ROLL' },
		{ code: 'LUSIN' },
		{ code: 'KODI' },
		{ code: 'DUS' },
		{ code: 'BOTOL' },
		{ code: 'GALON' },
		{ code: 'KALENG' },
		{ code: 'KARUNG' },
		{ code: 'RIM' },
		{ code: 'PASANG' },
		{ code: 'LEMBAR' },
	],
} as const
