// AUTO-GENERATED by scripts/generate-web.ts — DO NOT EDIT.

export * from './sales-type.dto'
export * from './sales-type.api'

/* --- manual exports (preserved) --- */
export * from './components/sales-type-form-dialog'
