// AUTO-GENERATED by scripts/generate-web.ts — DO NOT EDIT.

import { createPaginatedResponseSchema, createSuccessResponseSchema, zc } from '@/lib/validation'

import { endpoint } from '@/config/endpoint.gen'

import { apiFactory, createQueryKeys } from '@/lib/api'

import { SalesTypeCreateDto, SalesTypeDto, SalesTypeFilterDto, SalesTypeUpdateDto } from './sales-type.dto'

const salesTypeKeys = createQueryKeys('sales-type', 'sales-type')

export const salesTypeApi = {
	list: apiFactory({ method: 'get', url: endpoint['sales-type']['list'], params: SalesTypeFilterDto, result: createPaginatedResponseSchema(SalesTypeDto), queryKey: salesTypeKeys.list }),
	detail: apiFactory({ method: 'get', url: endpoint['sales-type']['detail'], params: zc.RecordId, result: createSuccessResponseSchema(SalesTypeDto), queryKey: (params) => salesTypeKeys.detail(params?.id) }),
	create: apiFactory({ method: 'post', url: endpoint['sales-type']['create'], body: SalesTypeCreateDto, result: createSuccessResponseSchema(zc.RecordId), invalidates: [salesTypeKeys.lists()] }),
	update: apiFactory({ method: 'put', url: endpoint['sales-type']['update'], body: SalesTypeUpdateDto, result: createSuccessResponseSchema(zc.RecordId), invalidates: [salesTypeKeys.lists()] }),
	remove: apiFactory({ method: 'delete', url: endpoint['sales-type']['remove'], body: zc.RecordId, result: createSuccessResponseSchema(zc.RecordId), invalidates: [salesTypeKeys.lists()] }),
}
