import type { Product } from "./types";

/**
 * Mock Product Data
 * Simulated product data for development
 */

export const MOCK_PRODUCTS: Array<Product> = [
  {
    id: "1",
    code: "RM-001",
    name: "Kain Katun Premium",
    description: "Kain katun berkualitas tinggi untuk produksi garmen",
    category: "raw-material",
    status: "active",
    unit: "meter",
    price: 85000,
    cost: 65000,
    stock: 1250,
    minStock: 200,
    maxStock: 2000,
    reorderPoint: 300,
    supplier: "PT Tekstil Indonesia",
    barcode: "8991234567890",
    sku: "KTN-PRM-001",
    weight: 0.3,
    tags: ["premium", "katun", "tekstil"],
    createdAt: new Date("2024-01-15"),
    updatedAt: new Date("2024-02-08"),
    createdBy: "admin",
    updatedBy: "admin",
  },
  {
    id: "2",
    code: "SF-002",
    name: "Kemeja Polos Putih",
    description: "Kemeja semi-finished siap untuk finishing",
    category: "semi-finished",
    status: "active",
    unit: "pcs",
    price: 125000,
    cost: 95000,
    stock: 450,
    minStock: 100,
    maxStock: 800,
    reorderPoint: 150,
    supplier: "CV Garmen Jaya",
    barcode: "8991234567891",
    sku: "KMJ-PLO-WHT",
    weight: 0.25,
    dimensions: {
      length: 70,
      width: 50,
      height: 2,
    },
    tags: ["kemeja", "putih", "semi-finished"],
    createdAt: new Date("2024-01-20"),
    updatedAt: new Date("2024-02-09"),
    createdBy: "admin",
    updatedBy: "manager",
  },
  {
    id: "3",
    code: "FG-003",
    name: "Kemeja Batik Eksklusif",
    description: "Kemeja batik ready to sell dengan packaging premium",
    category: "finished-goods",
    status: "active",
    unit: "pcs",
    price: 350000,
    cost: 220000,
    stock: 85,
    minStock: 20,
    maxStock: 200,
    reorderPoint: 30,
    barcode: "8991234567892",
    sku: "BTK-EKS-001",
    weight: 0.3,
    dimensions: {
      length: 75,
      width: 55,
      height: 3,
    },
    tags: ["batik", "eksklusif", "ready-to-sell"],
    createdAt: new Date("2024-01-25"),
    updatedAt: new Date("2024-02-10"),
    createdBy: "admin",
    updatedBy: "admin",
  },
  {
    id: "4",
    code: "RM-004",
    name: "Benang Polyester",
    description: "Benang jahit polyester untuk produksi massal",
    category: "raw-material",
    status: "active",
    unit: "roll",
    price: 45000,
    cost: 32000,
    stock: 580,
    minStock: 150,
    maxStock: 1000,
    reorderPoint: 200,
    supplier: "PT Benang Nusantara",
    barcode: "8991234567893",
    sku: "BNG-PLY-001",
    weight: 0.5,
    tags: ["benang", "polyester", "jahit"],
    createdAt: new Date("2024-02-01"),
    updatedAt: new Date("2024-02-09"),
    createdBy: "staff",
    updatedBy: "staff",
  },
  {
    id: "5",
    code: "CN-005",
    name: "Kancing Plastik 15mm",
    description: "Kancing plastik warna putih diameter 15mm",
    category: "consumable",
    status: "active",
    unit: "box",
    price: 25000,
    cost: 18000,
    stock: 320,
    minStock: 50,
    maxStock: 500,
    reorderPoint: 80,
    supplier: "CV Aksesoris Garmen",
    barcode: "8991234567894",
    sku: "KNC-PLT-15",
    weight: 0.1,
    tags: ["kancing", "plastik", "aksesoris"],
    createdAt: new Date("2024-02-03"),
    updatedAt: new Date("2024-02-08"),
    createdBy: "staff",
    updatedBy: "staff",
  },
  {
    id: "6",
    code: "FG-006",
    name: "Celana Jeans Premium",
    description: "Celana jeans denim premium dengan cutting modern",
    category: "finished-goods",
    status: "active",
    unit: "pcs",
    price: 425000,
    cost: 280000,
    stock: 120,
    minStock: 30,
    maxStock: 250,
    reorderPoint: 50,
    barcode: "8991234567895",
    sku: "JNS-PRM-001",
    weight: 0.6,
    dimensions: {
      length: 100,
      width: 40,
      height: 3,
    },
    tags: ["jeans", "denim", "premium"],
    createdAt: new Date("2024-02-05"),
    updatedAt: new Date("2024-02-10"),
    createdBy: "admin",
    updatedBy: "manager",
  },
  {
    id: "7",
    code: "RM-007",
    name: "Kain Denim Raw",
    description: "Kain denim mentah untuk produksi celana jeans",
    category: "raw-material",
    status: "active",
    unit: "meter",
    price: 125000,
    cost: 95000,
    stock: 680,
    minStock: 150,
    maxStock: 1200,
    reorderPoint: 250,
    supplier: "PT Denim Indonesia",
    barcode: "8991234567896",
    sku: "DNM-RAW-001",
    weight: 0.45,
    tags: ["denim", "raw", "jeans"],
    createdAt: new Date("2024-02-06"),
    updatedAt: new Date("2024-02-09"),
    createdBy: "staff",
    updatedBy: "staff",
  },
  {
    id: "8",
    code: "FG-008",
    name: "Jaket Bomber Limited",
    description: "Jaket bomber edisi terbatas dengan design eksklusif",
    category: "finished-goods",
    status: "active",
    unit: "pcs",
    price: 650000,
    cost: 420000,
    stock: 45,
    minStock: 10,
    maxStock: 100,
    reorderPoint: 20,
    barcode: "8991234567897",
    sku: "JKT-BMB-LTD",
    weight: 0.8,
    dimensions: {
      length: 65,
      width: 60,
      height: 5,
    },
    tags: ["jaket", "bomber", "limited"],
    createdAt: new Date("2024-02-07"),
    updatedAt: new Date("2024-02-10"),
    createdBy: "admin",
    updatedBy: "admin",
  },
  {
    id: "9",
    code: "CN-009",
    name: "Label Brand Premium",
    description: "Label woven premium untuk branding produk",
    category: "consumable",
    status: "active",
    unit: "pcs",
    price: 5000,
    cost: 3500,
    stock: 2500,
    minStock: 500,
    maxStock: 5000,
    reorderPoint: 800,
    supplier: "CV Label Printing",
    barcode: "8991234567898",
    sku: "LBL-BRD-PRM",
    weight: 0.01,
    tags: ["label", "branding", "woven"],
    createdAt: new Date("2024-02-08"),
    updatedAt: new Date("2024-02-09"),
    createdBy: "staff",
    updatedBy: "staff",
  },
  {
    id: "10",
    code: "SF-010",
    name: "Kaos Polos Hitam",
    description: "Kaos polos hitam siap untuk sablon/bordir",
    category: "semi-finished",
    status: "active",
    unit: "pcs",
    price: 45000,
    cost: 32000,
    stock: 850,
    minStock: 200,
    maxStock: 1500,
    reorderPoint: 300,
    supplier: "CV Kaos Polos",
    barcode: "8991234567899",
    sku: "KOS-PLO-BLK",
    weight: 0.2,
    tags: ["kaos", "polos", "hitam"],
    createdAt: new Date("2024-02-09"),
    updatedAt: new Date("2024-02-10"),
    createdBy: "staff",
    updatedBy: "manager",
  },
  {
    id: "11",
    code: "RM-011",
    name: "Kain Sutra Premium",
    description: "Kain sutra import berkualitas tinggi",
    category: "raw-material",
    status: "active",
    unit: "meter",
    price: 285000,
    cost: 220000,
    stock: 180,
    minStock: 50,
    maxStock: 400,
    reorderPoint: 80,
    supplier: "PT Import Tekstil",
    barcode: "8991234567900",
    sku: "STR-PRM-001",
    weight: 0.15,
    tags: ["sutra", "premium", "import"],
    createdAt: new Date("2024-01-10"),
    updatedAt: new Date("2024-02-05"),
    createdBy: "admin",
    updatedBy: "admin",
  },
  {
    id: "12",
    code: "FG-012",
    name: "Dress Casual Wanita",
    description: "Dress casual untuk wanita dengan design modern",
    category: "finished-goods",
    status: "discontinued",
    unit: "pcs",
    price: 280000,
    cost: 185000,
    stock: 15,
    minStock: 0,
    maxStock: 0,
    reorderPoint: 0,
    barcode: "8991234567901",
    sku: "DRS-CSL-WMN",
    weight: 0.35,
    tags: ["dress", "casual", "discontinued"],
    createdAt: new Date("2023-12-01"),
    updatedAt: new Date("2024-01-15"),
    createdBy: "admin",
    updatedBy: "manager",
  },
];

// Helper functions
export const getProductById = (id: string): Product | undefined => {
  return MOCK_PRODUCTS.find((p) => p.id === id);
};

export const getProductByCode = (code: string): Product | undefined => {
  return MOCK_PRODUCTS.find((p) => p.code === code);
};

export const getCategoryLabel = (category: Product["category"]): string => {
  const labels = {
    "raw-material": "Bahan Baku",
    "semi-finished": "Setengah Jadi",
    "finished-goods": "Barang Jadi",
    consumable: "Habis Pakai",
  };
  return labels[category];
};

export const getStatusLabel = (status: Product["status"]): string => {
  const labels = {
    active: "Aktif",
    inactive: "Tidak Aktif",
    discontinued: "Dihentikan",
  };
  return labels[status];
};

export const getUnitLabel = (unit: Product["unit"]): string => {
  const labels = {
    kg: "Kilogram",
    liter: "Liter",
    pcs: "Pcs",
    box: "Box",
    meter: "Meter",
    roll: "Roll",
  };
  return labels[unit];
};

export const formatCurrency = (amount: number): string => {
  return new Intl.NumberFormat("id-ID", {
    style: "currency",
    currency: "IDR",
    minimumFractionDigits: 0,
  }).format(amount);
};

export const getStockStatus = (
  stock: number,
  minStock: number,
  reorderPoint: number,
): "critical" | "low" | "normal" | "high" => {
  if (stock === 0) return "critical";
  if (stock < minStock) return "critical";
  if (stock < reorderPoint) return "low";
  return "normal";
};
