// AUTO-GENERATED by scripts/generate-web.ts — DO NOT EDIT.

/** Generated endpoint URL map. Do not edit by hand. */
export const endpoint = {
	auth: {
		login: 'auth/login',
		me: 'auth/me',
	},
	company: {
		detail: 'settings/detail',
		create: 'settings/create',
		update: 'settings/update',
	},
	crm: {
		list: 'customer/list',
		detail: 'customer/detail',
		byPhone: 'customer/by-phone',
		create: 'customer/create',
		update: 'customer/update',
		remove: 'customer/remove',
		addPoints: 'customer/points/add',
		redeemPoints: 'customer/points/redeem',
		loyaltyHistory: 'customer/loyalty-history',
	},
	iam: {
		role: {
			list: 'iam/role/list',
			detail: 'iam/role/detail',
			create: 'iam/role/create',
			update: 'iam/role/update',
			remove: 'iam/role/remove',
		},
		user: {
			list: 'iam/user/list',
			detail: 'iam/user/detail',
			create: 'iam/user/create',
			update: 'iam/user/update',
			changePassword: 'iam/user/change-password',
			adminPasswordReset: 'iam/user/admin/password-reset',
			remove: 'iam/user/remove',
		},
	},
	location: {
		list: 'location/list',
		detail: 'location/detail',
		create: 'location/create',
		update: 'location/update',
		remove: 'location/remove',
	},
	'sales-type': {
		list: 'sales-type/list',
		detail: 'sales-type/detail',
		create: 'sales-type/create',
		update: 'sales-type/update',
		remove: 'sales-type/remove',
	},
	supplier: {
		list: 'supplier/list',
		detail: 'supplier/detail',
		create: 'supplier/create',
		update: 'supplier/update',
		remove: 'supplier/remove',
	},
} as const
