// AUTO-GENERATED by scripts/generate-web.ts — DO NOT EDIT.

export * from './iam.dto'
export * from './role.api'
export * from './user.api'

/* --- manual exports (preserved) --- */
export * from './utils'
export * from './assignment.dto'
export * from './assignment.api'
