CREATE TABLE "company_settings" (
	"id" serial PRIMARY KEY,
	"name" text NOT NULL,
	"address" text,
	"phone" text,
	"email" text,
	"tax_id" text,
	"taxRate" numeric(5,2) DEFAULT '0' NOT NULL,
	"logo_url" text,
	"invoice_footer" text,
	"receipt_footer" text,
	"currency_code" text DEFAULT 'IDR' NOT NULL,
	"currency_symbol" text DEFAULT 'Rp' NOT NULL,
	"settings" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"deleted_at" timestamp with time zone,
	"created_by" integer NOT NULL,
	"updated_by" integer NOT NULL,
	"deleted_by" integer,
	"sync_at" timestamp with time zone
);
