#!/usr/bin/env bun
/**
 * Web codegen — contract-driven.
 *
 * Reads `defineContract(...)` descriptors from the server modules and emits, per
 * feature:
 *
 *   apps/web/src/features/<feature>/<feature>.dto.ts   (merged, copied DTOs)
 *   apps/web/src/features/<feature>/<entity>.api.ts    (typed api-factory calls)
 *   apps/web/src/features/<feature>/index.ts           (barrel)
 *   apps/web/src/config/endpoint.gen.ts                (URL map for all features)
 *
 * DTO copy rules:
 *   - copy the server contract source verbatim, then:
 *   - rewrite `@/shared/schema` → `@/lib/validation`
 *   - rewrite `@/modules/<x>`   → `@/features/<x>`
 *   - strip the `defineContract` import + the `export const …Contract` block
 *   - merge all entities of a feature into ONE `<feature>.dto.ts`; warn on any
 *     duplicate exported name across the merged files.
 *
 * Usage (from apps/server):
 *   bun run generate:web                 # all registered contracts
 *   bun run generate:web location        # one feature
 *   bun run generate:web:preview         # dry-run
 */

import type { HttpMethod, ModuleContract } from '@/shared/contract/define-contract'

import { readFileSync, writeFileSync, mkdirSync, existsSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import type { z } from 'zod'

// apps/server/scripts → apps/server → apps → <repo root>
const REPO_ROOT = resolve(import.meta.dir, '../../..')
const SERVER_MODULES = join(REPO_ROOT, 'apps/server/src/modules')
const WEB_FEATURES = join(REPO_ROOT, 'apps/web/src/features')
const ENDPOINT_GEN = join(REPO_ROOT, 'apps/web/src/config/endpoint.gen.ts')
const GEN_HEADER = `// AUTO-GENERATED by scripts/generate-web.ts — DO NOT EDIT.`

const METHODS: HttpMethod[] = ['get', 'post', 'put', 'patch', 'delete']

/* -------------------------------------------------------------------------- */
/*  Contract registry — add a module's contract path here after authoring it. */
/* -------------------------------------------------------------------------- */

const CONTRACT_PATHS = ['location/location.contract.ts', 'auth/auth.contract.ts']

async function loadContracts(): Promise<ModuleContract[]> {
	const contracts: ModuleContract[] = []
	for (const rel of CONTRACT_PATHS) {
		const mod: unknown = await import(join(SERVER_MODULES, rel))
		if (typeof mod !== 'object' || mod === null) continue
		for (const value of Object.values(mod)) {
			if (isModuleContract(value)) contracts.push(value)
		}
	}
	return contracts
}

function isModuleContract(v: unknown): v is ModuleContract {
	if (typeof v !== 'object' || v === null) return false
	return 'feature' in v && 'entity' in v && 'endpoints' in v && 'dtos' in v
}

/* -------------------------------------------------------------------------- */
/*  Endpoint normalization (from the terse authoring form)                    */
/* -------------------------------------------------------------------------- */

interface NormalizedEndpoint {
	action: string
	method: HttpMethod
	path: string
	input?: { kind: 'query' | 'body'; schema: z.ZodType }
	output: { paginated: boolean; schema: z.ZodType }
}

function normalizeEndpoints(contract: ModuleContract): NormalizedEndpoint[] {
	const result: NormalizedEndpoint[] = []
	for (const [action, def] of Object.entries(contract.endpoints)) {
		const method = METHODS.find((m) => typeof def[m] === 'string')
		if (!method) throw new Error(`Endpoint "${contract.feature}.${action}" has no HTTP method`)
		const path = def[method]
		if (typeof path !== 'string') continue

		let input: NormalizedEndpoint['input']
		if (def.query) input = { kind: 'query', schema: def.query }
		else if (def.body) input = { kind: 'body', schema: def.body }

		const paginated = Array.isArray(def.ok)
		const outSchema: z.ZodType = Array.isArray(def.ok) ? def.ok[0] : def.ok

		const normalized: NormalizedEndpoint = {
			action,
			method,
			path,
			output: { paginated, schema: outSchema },
		}
		if (input) normalized.input = input
		result.push(normalized)
	}
	return result
}

/** Resolve a schema object → the identifier to emit on the web side. */
function refOf(contract: ModuleContract, schema: z.ZodType): { name: string; shared: boolean } {
	for (const [name, s] of Object.entries(contract.dtos)) {
		if (s === schema) return { name, shared: false }
	}
	// Not a registered DTO → shared validation primitive (zc.X / zp.X / zq.X).
	// We can't recover its name from the object; the caller must special-case
	// known shared schemas. Fallback: treat as zc.RecordId-style unknown.
	const known = matchSharedRef(schema)
	if (known) return { name: known, shared: true }
	throw new Error(
		`Schema for an endpoint in "${contract.feature}" is neither in \`dtos\` nor a known shared ref. ` +
			`Add it to the contract's \`dtos\` map.`,
	)
}

/**
 * Known shared validation schemas that appear directly in contracts. Extend as
 * needed. Compared by identity against the server's `@/shared/schema` exports.
 */
let SHARED_REFS: Map<z.ZodType, string> | null = null
async function loadSharedRefs(): Promise<Map<z.ZodType, string>> {
	if (SHARED_REFS) return SHARED_REFS
	const schema: unknown = await import('@/shared/schema')
	const map = new Map<z.ZodType, string>()
	if (typeof schema === 'object' && schema !== null) {
		const mod = schema as { zc?: Record<string, z.ZodType>; zq?: Record<string, z.ZodType> }
		for (const [k, v] of Object.entries(mod.zc ?? {})) map.set(v, `zc.${k}`)
		for (const [k, v] of Object.entries(mod.zq ?? {})) map.set(v, `zq.${k}`)
	}
	SHARED_REFS = map
	return map
}
function matchSharedRef(schema: z.ZodType): string | undefined {
	return SHARED_REFS?.get(schema)
}

/* -------------------------------------------------------------------------- */
/*  DTO copy + merge                                                          */
/* -------------------------------------------------------------------------- */

/**
 * Build the merged `<feature>.dto.ts` from all contracts of a feature.
 * Returns the file content + a list of duplicate-name warnings.
 */
function generateDto(feature: string, contracts: ModuleContract[]): {
	path: string
	content: string
	warnings: string[]
} {
	const warnings: string[] = []
	const seenExports = new Map<string, string>() // exportName → source entity
	const imports = new Set<string>() // rewritten import lines (deduped)
	const reexports = new Set<string>() // cross-feature re-export lines (deduped)
	const bodies: string[] = []

	// Unique dtoSource files (a feature may have several entities/contracts).
	const sources = [...new Set(contracts.map((c) => c.dtoSource))]

	for (const src of sources) {
		const raw = readFileSync(join(SERVER_MODULES, src), 'utf-8')
		const { importLines, reexportLines, body } = transformDtoSource(raw)
		for (const imp of importLines) imports.add(imp)
		for (const re of reexportLines) reexports.add(re)

		// Detect duplicate export names across merged sources.
		for (const name of exportedNames(body)) {
			const prev = seenExports.get(name)
			if (prev && prev !== src) {
				warnings.push(`duplicate export "${name}" (in ${prev} and ${src})`)
			}
			seenExports.set(name, src)
		}
		bodies.push(body.trim())
	}

	const importBlock = [...imports].sort().join('\n')
	const reexportBlock = reexports.size > 0 ? '\n\n' + [...reexports].sort().join('\n') : ''
	const content = `${GEN_HEADER}\n${importBlock}${reexportBlock}\n\n${bodies.join('\n\n')}\n`

	return { path: join(WEB_FEATURES, feature, `${feature}.dto.ts`), content, warnings }
}

/**
 * Transform one server contract source into web-ready import/export lines +
 * body:
 *  - rewrite `@/shared/schema` → `@/lib/validation`
 *  - rewrite `@/modules/<x>`   → `@/features/<x>`, and convert those cross-feature
 *    imports into **re-exports** so the merged `<feature>.dto.ts` is the single
 *    import surface (the api file imports everything from it)
 *  - drop the `define-contract` import and the `export const …Contract` block
 */
function transformDtoSource(src: string): { importLines: string[]; reexportLines: string[]; body: string } {
	const out = src
		// drop the define-contract import line
		.replace(/^import\s+\{[^}]*\}\s+from\s+'@\/shared\/contract\/define-contract'\r?\n/mu, '')
		// drop the contract export block: `export const <x>Contract = defineContract({ ... })`
		.replace(/\nexport const \w+Contract = defineContract\(\{[\s\S]*?\n\}\)\n?/mu, '\n')
		// drop a `/* --- CONTRACT --- */` divider if present
		.replace(/\n\/\* -+ CONTRACT -+ \*\/\n?/mu, '\n')
		// rewrite validation import
		.replace(/from '@\/shared\/schema'/gu, "from '@/lib/validation'")
		// rewrite cross-module import specifiers → cross-feature
		.replace(/from '@\/modules\//gu, "from '@/features/")

	// Split leading imports from the body so a merge can dedupe imports.
	const importLines: string[] = []
	const reexportLines: string[] = []
	const bodyLines: string[] = []
	let inImports = true
	for (const line of out.split('\n')) {
		const t = line.trim()
		if (inImports && /^import\s/u.test(t)) {
			importLines.push(t)
			// Cross-feature imports are also re-exported so the merged dto is the
			// single import surface for the api file (which references borrowed DTOs).
			const cross = t.match(/^import (?:type )?(\{[^}]*\}) from '(@\/features\/[^']+)'/u)
			if (cross) reexportLines.push(`export ${cross[1]} from '${cross[2]}'`)
		} else if (inImports && t === '') {
			// skip blank lines between imports
		} else {
			inImports = false
			bodyLines.push(line)
		}
	}
	return { importLines, reexportLines, body: bodyLines.join('\n') }
}

/** Extract top-level exported identifiers (const/type/enum/function). */
function exportedNames(body: string): string[] {
	const names: string[] = []
	const re = /^export\s+(?:const|type|function|enum|interface)\s+(\w+)/gmu
	let m: RegExpExecArray | null
	while ((m = re.exec(body)) !== null) if (m[1]) names.push(m[1])
	return names
}

/* -------------------------------------------------------------------------- */
/*  API factory                                                               */
/* -------------------------------------------------------------------------- */

function generateApi(contract: ModuleContract, multiEntity: boolean): { path: string; content: string } {
	const { entity, feature } = contract
	const eps = normalizeEndpoints(contract)

	const dtoRefs = new Set<string>()
	const validationNamed = new Set<string>()

	const use = (schema: z.ZodType) => {
		const { name, shared } = refOf(contract, schema)
		if (shared) validationNamed.add(name.split('.')[0] ?? name)
		else dtoRefs.add(name)
		return name
	}

	// Pre-resolve refs + wrapper needs.
	const rows = eps.map((ep) => {
		const outName = use(ep.output.schema)
		const inName = ep.input ? use(ep.input.schema) : undefined
		validationNamed.add(
			ep.output.paginated ? 'createPaginatedResponseSchema' : 'createSuccessResponseSchema',
		)
		return { ep, outName, inName }
	})

	const lines: string[] = [GEN_HEADER, '']
	lines.push(`import { ${[...validationNamed].sort().join(', ')} } from '@/lib/validation'`)
	lines.push('')
	lines.push(`import { endpoint } from '@/config/endpoint.gen'`)
	lines.push('')
	lines.push(`import { apiFactory, createQueryKeys } from '@/lib/api'`)
	lines.push('')
	if (dtoRefs.size > 0) {
		lines.push(`import { ${[...dtoRefs].sort().join(', ')} } from './${feature}.dto'`)
		lines.push('')
	}

	const keys = `${camel(entity)}Keys`
	lines.push(`const ${keys} = createQueryKeys('${feature}', '${entity}')`)
	lines.push('')
	lines.push(`export const ${camel(entity)}Api = {`)

	for (const { ep, outName, inName } of rows) {
		const url = multiEntity
			? `endpoint.${feature}.${entity}.${ep.action}`
			: `endpoint.${feature}.${ep.action}`
		const result = ep.output.paginated
			? `createPaginatedResponseSchema(${outName})`
			: `createSuccessResponseSchema(${outName})`

		const props: string[] = [`method: '${ep.method}'`, `url: ${url}`]
		if (ep.input && inName) props.push(`${ep.input.kind === 'query' ? 'params' : 'body'}: ${inName}`)
		props.push(`result: ${result}`)
		if (ep.method === 'get' && ep.action === 'list') props.push(`queryKey: ${keys}.list`)
		else if (ep.method === 'get' && ep.action === 'detail')
			props.push(`queryKey: (params) => ${keys}.detail(params?.id)`)
		else if (ep.method !== 'get') props.push(`invalidates: [${keys}.lists()]`)

		lines.push(`\t${ep.action}: apiFactory({ ${props.join(', ')} }),`)
	}

	lines.push(`}`)
	return { path: join(WEB_FEATURES, feature, `${entity}.api.ts`), content: lines.join('\n') + '\n' }
}

/* -------------------------------------------------------------------------- */
/*  Endpoint config                                                           */
/* -------------------------------------------------------------------------- */

type EndpointNode = string | { [key: string]: EndpointNode }

function generateEndpointConfig(contracts: ModuleContract[]): string {
	const entityCount = new Map<string, number>()
	for (const c of contracts) entityCount.set(c.feature, (entityCount.get(c.feature) ?? 0) + 1)

	const tree: Record<string, EndpointNode> = {}
	for (const c of contracts) {
		const actions: Record<string, EndpointNode> = {}
		for (const ep of normalizeEndpoints(c)) actions[ep.action] = joinUrl(c.prefix, ep.path)

		if ((entityCount.get(c.feature) ?? 1) > 1) {
			const existing = tree[c.feature]
			const node: { [key: string]: EndpointNode } = typeof existing === 'object' ? existing : {}
			node[c.entity] = actions
			tree[c.feature] = node
		} else {
			tree[c.feature] = actions
		}
	}

	const body = Object.entries(tree)
		.sort((a, b) => a[0].localeCompare(b[0]))
		.map(([k, v]) => `\t${k}: ${renderNode(v, 2)},`)
		.join('\n')

	return `${GEN_HEADER}\n\n/** Generated endpoint URL map. Do not edit by hand. */\nexport const endpoint = {\n${body}\n} as const\n`
}

function renderNode(node: EndpointNode, indent: number): string {
	if (typeof node === 'string') return `'${node}'`
	const pad = '\t'.repeat(indent)
	const inner = Object.entries(node)
		.map(([k, v]) => `${pad}${k}: ${renderNode(v, indent + 1)},`)
		.join('\n')
	return `{\n${inner}\n${'\t'.repeat(indent - 1)}}`
}

function joinUrl(prefix: string, path: string): string {
	return `${prefix}${path}`.replace(/^\//u, '')
}

/* -------------------------------------------------------------------------- */
/*  Barrel + fs helpers                                                       */
/* -------------------------------------------------------------------------- */

function camel(s: string): string {
	return s.replace(/-([a-z])/gu, (_, c: string) => c.toUpperCase())
}

function writeFile(path: string, content: string, dryRun: boolean) {
	const rel = path.replace(REPO_ROOT + '/', '')
	if (dryRun) {
		console.log(`   [dry-run] ${rel}`)
		return
	}
	mkdirSync(dirname(path), { recursive: true })
	writeFileSync(path, content)
	console.log(`   ✓ ${rel}`)
}

/**
 * Feature barrel: generator owns the dto + api exports; hand-written exports go
 * below the marker and are preserved across regeneration.
 */
function writeFeatureBarrel(feature: string, entities: string[], dryRun: boolean) {
	const barrelPath = join(WEB_FEATURES, feature, 'index.ts')
	const MARKER = '/* --- manual exports (preserved) --- */'

	let manual = ''
	if (existsSync(barrelPath)) {
		const existing = readFileSync(barrelPath, 'utf-8')
		const idx = existing.indexOf(MARKER)
		if (idx === -1) {
			manual = existing
				.split('\n')
				.filter(
					(l) =>
						l.startsWith('export') &&
						!/\.\/[\w-]+\.(dto|api)'/u.test(l) &&
						!/\.\/(api|dto)'/u.test(l),
				)
				.join('\n')
				.trim()
		} else {
			manual = existing.slice(idx + MARKER.length).trim()
		}
	}

	const lines = [GEN_HEADER, '', `export * from './${feature}.dto'`]
	for (const entity of entities.sort()) lines.push(`export * from './${entity}.api'`)
	lines.push('', MARKER)
	if (manual) lines.push(manual)

	writeFile(barrelPath, lines.join('\n').trimEnd() + '\n', dryRun)
}

/* -------------------------------------------------------------------------- */
/*  Main                                                                      */
/* -------------------------------------------------------------------------- */

async function main() {
	const args = process.argv.slice(2)
	const dryRun = args.includes('--dry-run')
	const only = args.find((a) => !a.startsWith('--'))

	console.log('\n📋 Loading contracts...')
	await loadSharedRefs()
	const allContracts = await loadContracts()
	const targets = only ? allContracts.filter((c) => c.feature === only) : allContracts

	if (targets.length === 0) {
		console.log('   (no matching contracts)')
		return
	}
	console.log(`   found: ${targets.map((c) => `${c.feature}/${c.entity}`).join(', ')}`)

	const entityCount = new Map<string, number>()
	for (const c of allContracts) entityCount.set(c.feature, (entityCount.get(c.feature) ?? 0) + 1)

	// Group targets by feature (one merged DTO + one barrel per feature).
	const byFeature = new Map<string, ModuleContract[]>()
	for (const c of targets) byFeature.set(c.feature, [...(byFeature.get(c.feature) ?? []), c])

	console.log('\n🔨 Generating DTO + API...')
	let hadWarnings = false
	for (const [feature, group] of byFeature) {
		// All contracts of the feature (not just filtered) → complete merged DTO.
		const featureContracts = allContracts.filter((c) => c.feature === feature)

		const dtoFile = generateDto(feature, featureContracts)
		if (dtoFile.warnings.length > 0) {
			hadWarnings = true
			for (const w of dtoFile.warnings) console.warn(`   ⚠️  [${feature}] ${w}`)
		}
		writeFile(dtoFile.path, dtoFile.content, dryRun)

		for (const c of group) {
			const apiFile = generateApi(c, (entityCount.get(feature) ?? 1) > 1)
			writeFile(apiFile.path, apiFile.content, dryRun)
		}

		const entities = featureContracts.map((c) => c.entity)
		writeFeatureBarrel(feature, entities, dryRun)
	}

	console.log('\n🔨 Generating endpoint config...')
	writeFile(ENDPOINT_GEN, generateEndpointConfig(allContracts), dryRun)

	console.log(hadWarnings ? '\n⚠️  Done with warnings.\n' : '\n✅ Done!\n')
}

main().catch((err: unknown) => {
	console.error(err)
	process.exit(1)
})
