import { z } from 'zod'

/** Canonical permission vocabulary accepted by IAM role mutations. */
const PERMISSIONS = [
	'auth.me',
	'auth.logout',
	'auth.session.list',
	'auth.session.revoke',
	'company.read',
	'company.update',
	'location.read',
	'location.create',
	'location.update',
	'location.delete',
	'iam.read',
	'iam.create',
	'iam.update',
	'iam.delete',
	'uom.read',
	'uom.create',
	'uom.update',
	'uom.delete',
	'material.read',
	'material.create',
	'material.update',
	'material.delete',
	'supplier.read',
	'supplier.create',
	'supplier.update',
	'supplier.delete',
	'category.read',
	'category.create',
	'category.update',
	'category.delete',
	'item.read',
	'item.create',
	'item.update',
	'item.delete',
	'modifier.read',
	'modifier.create',
	'modifier.update',
	'modifier.delete',
	'recipe.read',
	'recipe.create',
	'recipe.update',
	'recipe.delete',
	'payment-method.read',
	'payment-method.create',
	'payment-method.update',
	'payment-method.delete',
	'order.read',
	'order.create',
	'order.update',
	'order.void',
	'payment.create',
	'shift.read',
	'shift.open',
	'shift.close',
	'shift.close-other',
	'discount.apply',
	'voucher.manage',
	'table.manage',
	'stock.read',
	'stock.adjust',
	'receiving.read',
	'receiving.create',
	'receiving.update',
	'receiving.confirm',
	'transfer.read',
	'transfer.create',
	'transfer.ship',
	'transfer.receive',
	'opname.read',
	'opname.create',
	'opname.update',
	'opname.complete',
	'production.read',
	'production.create',
	'production.update',
	'production.delete',
	'production.confirm',
	'audit.read',
] as const

const permissionSchema = z.enum(PERMISSIONS)
export const permissionsSchema = z.array(permissionSchema).default([])
